[package]
name = "sampler-uvi"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "Apache-2.0"
publish = false

[dependencies]
sampler-ir = { path = "../sampler-ir" }
sampler-core = { path = "../sampler-core" }
sampler-kontakt = { path = "../sampler-kontakt" }
roxmltree = "=0.21.1"

[lints.rust]
unsafe_code = "forbid"
