//! The KSP runtime: script slots, note events, callback scheduling and the engine
//! boundary. Everything reachable from MIDI input and `process` is preallocated;
//! steady-state event handling neither allocates nor locks.
//!
//! Events flow slot by slot. A note, release or controller event runs the matching
//! callback in slot N; unless the callback ignores it, the event moves to slot N+1
//! when the callback first yields (finishes or waits). After the last slot it
//! reaches the engine. Notes generated by `play_note` in slot N start at N+1.

use super::builtins::{self as b, CC_SLOTS, SysArray};
use super::compile::{self, Callback, Program, Setup, Ty, VarId};
use super::engine::{Fade, GroupMask, KspEngine, NoteLength, NoteSpec, VoiceId};
use super::vm::{self, Ctx, Forward, Kind, Machine, POLY_ROWS, SlotState, Stacks, Thread, Yield};
use super::{HostState, Interface, Value};
use anyhow::{Result, bail};
use std::borrow::Cow;
use std::cmp::Reverse;
use std::collections::{BTreeMap, BTreeSet, BinaryHeap, VecDeque};

pub const MAX_SLOTS: usize = 5;
pub const EVENT_CAPACITY: usize = 4096;
const EVENT_INDEX_BITS: u32 = 12;
const MAX_CHILDREN: usize = 8;
const THREAD_CAPACITY: usize = 1024;
const TIMER_CAPACITY: usize = 8192;
const WORK_CAPACITY: usize = 4096;
const FAULT_CAPACITY: usize = 256;
/// Instructions one callback may run between waits.
pub const CALLBACK_FUEL: u64 = 5_000_000;
/// Instructions all callbacks together may run per audio block; the rest is deferred.
pub const BLOCK_FUEL: u64 = 2_000_000;
/// `on init` runs off the audio thread and may do far more work.
pub const INIT_FUEL: u64 = 1_000_000_000;

/// Saved values of persistent variables, per script slot, keyed by variable name.
pub type Persisted = BTreeMap<String, Value>;

#[derive(Clone, Copy, Debug)]
pub struct Event {
    generation: u16,
    pub live: bool,
    pub note: i32,
    pub velocity: i32,
    pub pars: [i32; 4],
    pub volume: i32,
    pub tune: i32,
    pub pan: i32,
    pub zone: i32,
    pub sample_offset_us: i64,
    pub length: NoteLength,
    pub groups: GroupMask,
    pub marks: u32,
    /// -1 for MIDI, otherwise the generating slot.
    pub source: i32,
    /// First slot that sees this event.
    pub origin: u8,
    /// Slots that have run (or skipped) this note, i.e. the next slot index.
    pub reached: u8,
    /// Slots whose release processing has started, as a bitmask.
    pub released: u8,
    pub parent: i32,
    pub children: [i32; MAX_CHILDREN],
    pub child_count: u8,
    /// `play_note(..., -1)`: released with its parent.
    pub follows_parent: bool,
    pub ignored: bool,
    pub release_ignored: bool,
    pub at_engine: bool,
    pub voice: Option<VoiceId>,
    /// MIDI key still down.
    pub held: bool,
    pub fade_in_us: i32,
}

impl Event {
    const EMPTY: Self = Self {
        generation: 0,
        live: false,
        note: 0,
        velocity: 0,
        pars: [0; 4],
        volume: 0,
        tune: 0,
        pan: 0,
        zone: -1,
        sample_offset_us: 0,
        length: NoteLength::UntilNoteOff,
        groups: GroupMask::all(),
        marks: 0,
        source: -1,
        origin: 0,
        reached: 0,
        released: 0,
        parent: 0,
        children: [0; MAX_CHILDREN],
        child_count: 0,
        follows_parent: false,
        ignored: false,
        release_ignored: false,
        at_engine: false,
        voice: None,
        held: false,
        fade_in_us: 0,
    };

    pub fn index(id: i32) -> usize {
        (id as u32 & ((1 << EVENT_INDEX_BITS) - 1)) as usize
    }
}

/// Fixed pool of events. Freed events stay addressable until their slot is reused
/// (FIFO), so late `note_off`/`fade_out` calls on finished notes still resolve.
pub struct Events {
    slots: Vec<Event>,
    free: VecDeque<u32>,
}

impl Events {
    fn new() -> Self {
        Self { slots: vec![Event::EMPTY; EVENT_CAPACITY], free: (0..EVENT_CAPACITY as u32).collect() }
    }

    fn alloc(&mut self) -> Option<i32> {
        let i = self.free.pop_front()?;
        let e = &mut self.slots[i as usize];
        let generation = e.generation % 0x7FFF + 1;
        *e = Event { generation, live: true, ..Event::EMPTY };
        Some(i32::from(generation) << EVENT_INDEX_BITS | i as i32)
    }

    pub fn get(&self, id: i32) -> Option<&Event> {
        let e = self.slots.get(Event::index(id))?;
        (id > 0 && i32::from(e.generation) == id >> EVENT_INDEX_BITS).then_some(e)
    }

    pub fn get_mut(&mut self, id: i32) -> Option<&mut Event> {
        let e = self.slots.get_mut(Event::index(id))?;
        (id > 0 && i32::from(e.generation) == id >> EVENT_INDEX_BITS).then_some(e)
    }

    fn free(&mut self, id: i32) {
        if let Some(e) = self.get_mut(id).filter(|e| e.live) {
            e.live = false;
            self.free.push_back(Event::index(id) as u32);
        }
    }

    /// Whether the key behind this event (or its ancestors) is still down.
    pub fn held(&self, mut id: i32) -> bool {
        for _ in 0..8 {
            let Some(e) = self.get(id) else { return false };
            if e.source < 0 {
                return e.held;
            }
            id = e.parent;
        }
        false
    }

    /// Live event IDs addressed by a plain ID, `by_marks` value or `$ALL_EVENTS`.
    pub fn targets(&self, id: i32, out: &mut Vec<i32>) {
        out.clear();
        if id == b::ALL_EVENTS || (id & b::MARKS_FLAG != 0 && id > 0) {
            let marks = (id & !b::MARKS_FLAG) as u32;
            for (i, e) in self.slots.iter().enumerate() {
                if e.live && (id == b::ALL_EVENTS || e.marks & marks != 0) {
                    out.push(i32::from(e.generation) << EVENT_INDEX_BITS | i as i32);
                }
            }
        } else if self.get(id).is_some() {
            out.push(id);
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub enum Work {
    Note { event: i32, slot: u8 },
    Release { event: i32, slot: u8 },
    Controller { cc: u8, value: i32, slot: u8 },
    PolyAt { note: u8, value: i32, slot: u8 },
    Rpn { nrpn: bool, address: i32, value: i32, slot: u8 },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum TimerKind {
    Resume { thread: u16, generation: u32 },
    Release { event: i32, slot: u8 },
    Listener { slot: u8, generation: u32 },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Timer {
    at: u64,
    seq: u64,
    kind: TimerKind,
}

#[derive(Clone, Copy, Debug)]
struct FaultRecord {
    slot: u8,
    pc: u32,
    what: &'static str,
    count: u32,
}

/// Live MIDI state shared by all slots.
pub struct Input {
    pub cc: [i32; CC_SLOTS],
    pub pitch_bend: i32,
    /// MIDI events per key, newest last; zero marks an empty entry.
    keys: [[i32; 4]; 128],
}

/// Shared runtime state visible to builtins.
pub struct Env {
    pub host: HostState,
    pub events: Events,
    pub input: Input,
    pub work: VecDeque<Work>,
    timers: BinaryHeap<Reverse<Timer>>,
    timer_seq: u64,
    /// Sample time at the start of the current block, and the offset within it.
    pub now: u64,
    pub offset: u32,
    pub sample_rate: f64,
    pub tempo: f64,
    pub transport: bool,
    pub timer_origin: u64,
    pub block_fuel: u64,
    pub targets: Vec<i32>,
    pub message: String,
    pub engine_pars: BTreeMap<super::engine::EnginePar, i32>,
    pub saved_arrays: BTreeMap<(u8, VarId), Value>,
    pub persisted: Vec<Persisted>,
    pub notes: BTreeSet<Cow<'static, str>>,
    faults: Vec<FaultRecord>,
    rng: u64,
    next_callback_id: i32,
    next_async_id: i32,
    pub async_done: Vec<(u8, i32, i32)>,
    pub stop_waits: Vec<(i32, i32)>,
    pub listeners_changed: u8,
    pub pgs_changed: bool,
}

impl Env {
    fn new(host: HostState, persisted: Vec<Persisted>) -> Self {
        Self {
            host,
            events: Events::new(),
            input: Input { cc: [0; CC_SLOTS], pitch_bend: 0, keys: [[0; 4]; 128] },
            work: VecDeque::with_capacity(WORK_CAPACITY),
            timers: BinaryHeap::with_capacity(TIMER_CAPACITY),
            timer_seq: 0,
            now: 0,
            offset: 0,
            sample_rate: 48_000.0,
            tempo: 120.0,
            transport: false,
            timer_origin: 0,
            block_fuel: BLOCK_FUEL,
            targets: Vec::with_capacity(EVENT_CAPACITY),
            message: String::with_capacity(256),
            engine_pars: BTreeMap::new(),
            saved_arrays: BTreeMap::new(),
            persisted,
            notes: BTreeSet::new(),
            faults: Vec::with_capacity(FAULT_CAPACITY),
            rng: 0x9E37_79B9_7F4A_7C15,
            next_callback_id: 0,
            next_async_id: 0,
            async_done: Vec::with_capacity(64),
            stop_waits: Vec::with_capacity(64),
            listeners_changed: 0,
            pgs_changed: false,
        }
    }

    /// Absolute sample time of the executing callback.
    pub fn clock(&self) -> u64 {
        self.now + u64::from(self.offset)
    }

    pub fn micros(&self, samples: u64) -> i64 {
        (samples as f64 * 1e6 / self.sample_rate) as i64
    }

    pub fn samples(&self, us: i64) -> u64 {
        (us.max(0) as f64 * self.sample_rate / 1e6).round() as u64
    }

    pub fn quarter_us(&self) -> i32 {
        (60e6 / self.tempo) as i32
    }

    pub fn note(&mut self, text: &'static str) {
        if !self.notes.contains(text) {
            self.notes.insert(Cow::Borrowed(text));
        }
    }

    pub fn random(&mut self, lo: i32, hi: i32) -> i32 {
        self.rng ^= self.rng << 13;
        self.rng ^= self.rng >> 7;
        self.rng ^= self.rng << 17;
        let (lo, hi) = (lo.min(hi) as i64, lo.max(hi) as i64);
        (lo + (self.rng % (hi - lo + 1) as u64) as i64) as i32
    }

    pub fn next_async(&mut self) -> i32 {
        self.next_async_id = self.next_async_id % i32::MAX + 1;
        self.next_async_id
    }

    pub fn queue(&mut self, w: Work) {
        if self.work.len() < WORK_CAPACITY {
            self.work.push_back(w);
        } else {
            self.note("KSP event queue full; event dropped");
        }
    }

    fn timer(&mut self, at: u64, kind: TimerKind) {
        if self.timers.len() >= TIMER_CAPACITY {
            self.note("KSP timer queue full; wait dropped");
            return;
        }
        self.timer_seq += 1;
        self.timers.push(Reverse(Timer { at, seq: self.timer_seq, kind }));
    }

    pub fn release_after(&mut self, event: i32, slot: u8, us: i64) {
        let at = self.clock() + self.samples(us).max(1);
        self.timer(at, TimerKind::Release { event, slot });
    }

    fn fault(&mut self, slot: u8, pc: u32, what: &'static str) {
        if let Some(f) = self.faults.iter_mut().find(|f| f.slot == slot && f.pc == pc && f.what == what) {
            f.count = f.count.saturating_add(1);
        } else if self.faults.len() < FAULT_CAPACITY {
            self.faults.push(FaultRecord { slot, pc, what, count: 1 });
        }
    }

    /// Create a note event for `play_note` in `slot`, queued for the next slot.
    pub fn play_note(&mut self, slot: u8, parent: i32, note: i32, velocity: i32, offset_us: i32, duration_us: i32) -> i32 {
        let Some(id) = self.events.alloc() else {
            self.note("KSP event pool exhausted; play_note ignored");
            return 0;
        };
        let parent_state = self.events.get(parent).map(|p| (p.groups, p.released & (1 << slot) != 0));
        let e = self.events.get_mut(id).expect("fresh event");
        e.note = note;
        e.velocity = velocity;
        e.sample_offset_us = i64::from(offset_us);
        e.source = i32::from(slot);
        e.origin = slot + 1;
        e.reached = slot + 1;
        e.parent = parent;
        e.length = if duration_us == 0 { NoteLength::Sample } else { NoteLength::UntilNoteOff };
        e.follows_parent = duration_us < 0 && parent_state.is_some();
        if let Some((groups, _)) = parent_state {
            e.groups = groups;
        }
        self.queue(Work::Note { event: id, slot: slot + 1 });
        match parent_state {
            Some((_, true)) if duration_us < 0 => self.queue(Work::Release { event: id, slot: slot + 1 }),
            Some(_) if duration_us < 0 => {
                if let Some(p) = self.events.get_mut(parent) {
                    if (p.child_count as usize) < MAX_CHILDREN {
                        p.children[p.child_count as usize] = id;
                        p.child_count += 1;
                    } else {
                        self.note("Too many notes follow one parent; extra notes release after 1 s");
                        self.release_after(id, slot + 1, 1_000_000);
                    }
                }
            }
            _ if duration_us > 0 => self.release_after(id, slot + 1, i64::from(duration_us)),
            _ => {}
        }
        id
    }

    /// Stop a note from `slot` downstream: its release starts after the caller.
    pub fn note_off(&mut self, slot: u8, id: i32) {
        if let Some(e) = self.events.get(id) {
            let start = (slot + 1).max(e.origin);
            self.queue(Work::Release { event: id, slot: start });
        }
    }
}

pub struct Runtime {
    programs: Vec<Program>,
    states: Vec<SlotState>,
    pub env: Env,
    stacks: Stacks,
    threads: Vec<Thread>,
    free_threads: Vec<u16>,
    outputs: usize,
}

impl Runtime {
    pub fn new(host: HostState, outputs: usize, persisted: Vec<Persisted>) -> Self {
        Self {
            programs: Vec::new(),
            states: Vec::new(),
            env: Env::new(host, persisted),
            stacks: Stacks::with_capacity(1024),
            threads: vec![Thread::default(); THREAD_CAPACITY],
            free_threads: (0..THREAD_CAPACITY as u16).rev().collect(),
            outputs,
        }
    }

    /// Build a runtime from an instrument's scripts. Slots that fail stay present but
    /// disabled (events pass through them); their errors are returned per slot.
    pub fn with_scripts(
        scripts: &[impl AsRef<str>],
        engine: &mut dyn KspEngine,
        outputs: usize,
        persisted: Vec<Persisted>,
    ) -> (Self, Vec<Option<String>>) {
        let mut rt = Self::new(HostState::default(), outputs, persisted);
        let errors = scripts
            .iter()
            .take(MAX_SLOTS)
            .map(|s| rt.load(engine, s.as_ref()).err().map(|e| format!("{e:#}")))
            .collect();
        (rt, errors)
    }

    pub fn slots(&self) -> usize {
        self.programs.len()
    }

    pub fn host(&self) -> &HostState {
        &self.env.host
    }

    pub fn into_host(self) -> HostState {
        self.env.host
    }

    pub fn now(&self) -> u64 {
        self.env.now
    }

    pub fn set_tempo(&mut self, bpm: f64) {
        if bpm.is_finite() && bpm > 0.0 {
            self.env.tempo = bpm;
        }
    }

    /// Compile a script into the next slot and run `on init`. Shared host state is
    /// committed only if initialization succeeds.
    pub fn load(&mut self, engine: &mut dyn KspEngine, source: &str) -> Result<()> {
        if self.programs.len() >= MAX_SLOTS {
            bail!("At most {MAX_SLOTS} script slots");
        }
        self.env.sample_rate = engine.sample_rate();
        let index = self.programs.len() as u8;
        let setup = Setup { groups: engine.group_count(), outputs: self.outputs };
        let program = match compile::compile(source, &setup) {
            Ok(p) => p,
            Err(e) => {
                self.programs.push(Program::default());
                let mut state = SlotState::new(index, &self.programs[index as usize]);
                state.error = Some(format!("{e:#}"));
                self.states.push(state);
                return Err(e);
            }
        };
        self.states.push(SlotState::new(index, &program));
        self.programs.push(program);
        let staged = self.env.host.clone();
        if let Err(e) = self.run_init(engine, index) {
            self.env.host = staged;
            self.states[index as usize].error = Some(format!("{e:#}"));
            return Err(e);
        }
        self.restore_persistent(index);
        self.spawn_cb(engine, index, Callback::PersistenceChanged, Ctx::new(index, Kind::Cb(Callback::PersistenceChanged)));
        self.settle(engine);
        Ok(())
    }

    fn run_init(&mut self, engine: &mut dyn KspEngine, slot: u8) -> Result<()> {
        let prog = &self.programs[slot as usize];
        let entry = prog.callback(Callback::Init).expect("compiler requires on init");
        let mut t = Thread { pc: entry, live: true, ctx: Ctx::new(slot, Kind::Cb(Callback::Init)), ..Thread::default() };
        t.ctx.poly_row = POLY_ROWS - 1;
        let mut fuel = INIT_FUEL;
        let saved_fuel = std::mem::replace(&mut self.env.block_fuel, INIT_FUEL);
        let result = vm::exec(
            &mut Machine {
                prog,
                slot: &mut self.states[slot as usize],
                env: &mut self.env,
                stk: &mut self.stacks,
                engine,
                t: &mut t,
            },
            &mut fuel,
        );
        self.env.block_fuel = saved_fuel;
        match result {
            Ok(Yield::Done) => {}
            Ok(Yield::Wait(_)) => bail!("KSP line {}: wait() is not allowed in on init", prog.line(t.pc - 1)),
            Ok(Yield::OutOfFuel) => bail!("KSP execution budget exhausted in on init"),
            Err(f) => bail!("KSP line {}: {}", prog.line(t.pc.saturating_sub(1)), f.0),
        }
        // Work queued during init (e.g. set_controller) is dropped: nothing plays yet.
        self.env.work.clear();
        Ok(())
    }

    fn restore_persistent(&mut self, slot: u8) {
        let Some(saved) = self.env.persisted.get(slot as usize) else { return };
        let (prog, state) = (&self.programs[slot as usize], &mut self.states[slot as usize]);
        for &v in &state.persistent {
            let var = &prog.vars[v as usize];
            if let Some(value) = saved.get(&*var.name) {
                write_value(&mut state.mem, var, value);
            }
        }
    }

    /// Snapshot of persistent variables for every slot, for the host to save.
    pub fn persistence(&self) -> Vec<Persisted> {
        self.programs
            .iter()
            .zip(&self.states)
            .map(|(prog, state)| {
                state
                    .persistent
                    .iter()
                    .map(|&v| {
                        let var = &prog.vars[v as usize];
                        (var.name.to_string(), read_value(&state.mem, var))
                    })
                    .collect()
            })
            .collect()
    }

    pub fn interface(&self, slot: usize) -> Interface {
        self.states[slot].ui.interface(&self.programs[slot], &self.states[slot].mem)
    }

    /// Slot errors, runtime faults (with script line numbers) and service notes.
    pub fn diagnostics(&self) -> Vec<String> {
        let mut out: Vec<String> = self
            .states
            .iter()
            .enumerate()
            .filter_map(|(i, s)| s.error.as_ref().map(|e| format!("Slot {}: {e}", i + 1)))
            .collect();
        for (i, p) in self.programs.iter().enumerate() {
            out.extend(p.errors.iter().map(|e| format!("Slot {}: callback disabled: {e}", i + 1)));
        }
        out.extend(self.env.faults.iter().map(|f| {
            let line = self.programs[f.slot as usize].line(f.pc.saturating_sub(1));
            format!("Slot {} line {line}: {} ({}x)", f.slot + 1, f.what, f.count)
        }));
        out.extend(self.env.notes.iter().map(|n| n.to_string()));
        out
    }

    pub fn last_message(&self) -> &str {
        &self.env.message
    }

    // ---- Host input ------------------------------------------------------------------

    pub fn note_on(&mut self, engine: &mut dyn KspEngine, at: u32, note: u8, velocity: u8) {
        if velocity == 0 {
            return self.note_off(engine, at, note);
        }
        self.advance(engine, at);
        let note = note.min(127);
        self.set_sys(SysArray::KeyDown, note as usize, 1);
        let Some(id) = self.env.events.alloc() else {
            self.env.note("KSP event pool exhausted; note dropped");
            return;
        };
        let e = self.env.events.get_mut(id).expect("fresh event");
        e.note = i32::from(note);
        e.velocity = i32::from(velocity);
        e.held = true;
        let keys = &mut self.env.input.keys[note as usize];
        if let Some(free) = keys.iter_mut().find(|k| **k == 0) {
            *free = id;
        } else {
            keys.rotate_left(1);
            keys[3] = id;
        }
        self.env.queue(Work::Note { event: id, slot: 0 });
        self.settle(engine);
    }

    pub fn note_off(&mut self, engine: &mut dyn KspEngine, at: u32, note: u8) {
        self.advance(engine, at);
        let note = note.min(127);
        self.set_sys(SysArray::KeyDown, note as usize, 0);
        let keys = std::mem::take(&mut self.env.input.keys[note as usize]);
        for id in keys.into_iter().filter(|&id| id != 0) {
            if let Some(e) = self.env.events.get_mut(id) {
                e.held = false;
                self.env.queue(Work::Release { event: id, slot: 0 });
            }
        }
        self.settle(engine);
    }

    /// Controller 0..127; use `pitch_bend`/`channel_pressure` for the virtual ones.
    pub fn controller(&mut self, engine: &mut dyn KspEngine, at: u32, cc: u8, value: u8) {
        self.cc(engine, at, cc.min(127), i32::from(value));
    }

    /// Pitch bend, -8192..8191.
    pub fn pitch_bend(&mut self, engine: &mut dyn KspEngine, at: u32, value: i32) {
        self.env.input.pitch_bend = value.clamp(-8192, 8191);
        self.cc(engine, at, b::VCC_PITCH_BEND as u8, value.clamp(-8192, 8191));
    }

    pub fn channel_pressure(&mut self, engine: &mut dyn KspEngine, at: u32, value: u8) {
        self.cc(engine, at, b::VCC_MONO_AT as u8, i32::from(value));
    }

    fn cc(&mut self, engine: &mut dyn KspEngine, at: u32, cc: u8, value: i32) {
        self.advance(engine, at);
        self.env.input.cc[cc as usize] = value;
        self.env.queue(Work::Controller { cc, value, slot: 0 });
        self.settle(engine);
    }

    pub fn poly_pressure(&mut self, engine: &mut dyn KspEngine, at: u32, note: u8, value: u8) {
        self.advance(engine, at);
        self.env.queue(Work::PolyAt { note: note.min(127), value: i32::from(value), slot: 0 });
        self.settle(engine);
    }

    pub fn rpn(&mut self, engine: &mut dyn KspEngine, at: u32, nrpn: bool, address: u16, value: u16) {
        self.advance(engine, at);
        self.env.queue(Work::Rpn { nrpn, address: i32::from(address), value: i32::from(value), slot: 0 });
        self.settle(engine);
    }

    /// A host-side edit of control `control` (index into `Interface::controls`).
    pub fn ui_control(&mut self, engine: &mut dyn KspEngine, slot: usize, control: usize, value: i32) {
        let Some(state) = self.states.get_mut(slot) else { return };
        let Some(c) = state.ui.controls.get(control) else { return };
        let v = c.var;
        let prog = &self.programs[slot];
        let var = &prog.vars[v as usize];
        if var.ty == Ty::Int && var.len.is_none() {
            state.mem.ints[var.slot as usize] = value;
        }
        if let Some(entry) = prog.ui_callbacks[v as usize] {
            let ctx = Ctx::new(slot as u8, Kind::UiControl);
            self.spawn(engine, entry, ctx);
        }
        self.spawn_cb(engine, slot as u8, Callback::UiUpdate, Ctx::new(slot as u8, Kind::Cb(Callback::UiUpdate)));
        self.settle(engine);
    }

    pub fn set_transport(&mut self, engine: &mut dyn KspEngine, playing: bool) {
        if self.env.transport == playing {
            return;
        }
        self.env.transport = playing;
        let signal = if playing { b::signal::TRANSP_START } else { b::signal::TRANSP_STOP };
        for slot in 0..self.states.len() as u8 {
            if self.states[slot as usize].listener.transport {
                let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Listener));
                ctx.signal = signal;
                self.spawn_cb(engine, slot, Callback::Listener, ctx);
            }
        }
        self.settle(engine);
    }

    /// Finish the current block: resume every callback due before its end.
    pub fn process(&mut self, engine: &mut dyn KspEngine, frames: u32) {
        let end = self.env.now + u64::from(frames);
        self.run_timers(engine, end);
        if self.env.block_fuel == 0 {
            self.env.note("KSP instruction budget exhausted for a block; callbacks deferred");
        }
        self.env.now = end;
        self.env.offset = 0;
        self.env.block_fuel = BLOCK_FUEL;
    }

    fn advance(&mut self, engine: &mut dyn KspEngine, at: u32) {
        self.run_timers(engine, self.env.now + u64::from(at));
        self.env.offset = at;
    }

    fn run_timers(&mut self, engine: &mut dyn KspEngine, until: u64) {
        while let Some(&Reverse(t)) = self.env.timers.peek() {
            if t.at >= until || self.env.block_fuel == 0 {
                break;
            }
            self.env.timers.pop();
            self.env.offset = t.at.saturating_sub(self.env.now) as u32;
            match t.kind {
                TimerKind::Resume { thread, generation } => {
                    let th = &mut self.threads[thread as usize];
                    if th.live && th.generation == generation {
                        th.waiting = false;
                        self.resume(engine, thread);
                    }
                }
                TimerKind::Release { event, slot } => self.env.queue(Work::Release { event, slot }),
                TimerKind::Listener { slot, generation } => {
                    let l = self.states[slot as usize].listener;
                    if l.generation == generation {
                        let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Listener));
                        ctx.signal = if l.timer_us > 0 { b::signal::TIMER_MS } else { b::signal::TIMER_BEAT };
                        self.spawn_cb(engine, slot, Callback::Listener, ctx);
                        self.schedule_listener(slot, t.at);
                    }
                }
            }
            self.settle(engine);
        }
    }

    fn schedule_listener(&mut self, slot: u8, from: u64) {
        let l = self.states[slot as usize].listener;
        let us = if l.timer_us > 0 {
            i64::from(l.timer_us)
        } else if l.beats > 0 {
            i64::from(self.env.quarter_us() / l.beats)
        } else {
            return;
        };
        let at = from + self.env.samples(us).max(1);
        self.env.timer(at, TimerKind::Listener { slot, generation: l.generation });
    }

    // ---- Scheduling ------------------------------------------------------------------

    /// Drain queued work and the follow-up callbacks it triggers.
    fn settle(&mut self, engine: &mut dyn KspEngine) {
        loop {
            while let Some(w) = self.env.work.pop_front() {
                self.handle(engine, w);
            }
            if !self.env.stop_waits.is_empty() {
                self.stop_waits(engine);
                continue;
            }
            if self.env.listeners_changed != 0 {
                let changed = std::mem::take(&mut self.env.listeners_changed);
                for slot in 0..self.states.len() as u8 {
                    if changed & (1 << slot) != 0 {
                        self.schedule_listener(slot, self.env.clock());
                    }
                }
            }
            if let Some((slot, id, status)) = self.env.async_done.pop() {
                let mut ctx = Ctx::new(slot, Kind::Cb(Callback::AsyncComplete));
                ctx.async_id = id;
                ctx.async_status = status;
                self.spawn_cb(engine, slot, Callback::AsyncComplete, ctx);
                continue;
            }
            if std::mem::take(&mut self.env.pgs_changed) {
                for slot in 0..self.states.len() as u8 {
                    self.spawn_cb(engine, slot, Callback::PgsChanged, Ctx::new(slot, Kind::Cb(Callback::PgsChanged)));
                }
                // Changes made inside pgs_changed are delivered on the next pass.
                if !self.env.work.is_empty() || !self.env.async_done.is_empty() {
                    continue;
                }
                self.env.pgs_changed = false;
            }
            break;
        }
    }

    fn stop_waits(&mut self, engine: &mut dyn KspEngine) {
        while let Some((id, mode)) = self.env.stop_waits.pop() {
            let Some(i) = self.threads.iter().position(|t| t.live && t.waiting && t.ctx.callback_id == id) else {
                continue;
            };
            let t = &mut self.threads[i];
            t.generation = t.generation.wrapping_add(1);
            t.waiting = false;
            if mode == 0 {
                self.resume(engine, i as u16);
            } else {
                self.finish(i as u16);
            }
        }
    }

    fn enabled(&self, slot: u8) -> bool {
        self.states[slot as usize].error.is_none()
    }

    fn entry(&self, slot: u8, cb: Callback) -> Option<u32> {
        if self.enabled(slot) { self.programs[slot as usize].callback(cb) } else { None }
    }

    fn handle(&mut self, engine: &mut dyn KspEngine, w: Work) {
        let slots = self.programs.len() as u8;
        match w {
            Work::Note { event, slot } => {
                let Some(e) = self.env.events.get_mut(event) else { return };
                if std::mem::take(&mut e.ignored) {
                    if e.length == NoteLength::Sample {
                        self.env.events.free(event);
                    }
                    return;
                }
                if slot >= slots {
                    return self.play(engine, event);
                }
                e.reached = slot + 1;
                match self.entry(slot, Callback::Note) {
                    Some(_) => {
                        let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Note));
                        ctx.event = event;
                        ctx.poly_row = Event::index(event) as u32;
                        ctx.forward = Forward::Note;
                        self.spawn_cb(engine, slot, Callback::Note, ctx);
                    }
                    None => self.env.queue(Work::Note { event, slot: slot + 1 }),
                }
            }
            Work::Release { event, slot } => {
                let Some(e) = self.env.events.get_mut(event) else { return };
                if slot >= slots {
                    if let Some(v) = e.voice.take() {
                        engine.note_off(self.env.offset, v);
                    }
                    return self.env.events.free(event);
                }
                if slot >= e.reached || e.released & (1 << slot) != 0 {
                    return self.env.events.free(event);
                }
                e.released |= 1 << slot;
                let children = e.children;
                let count = e.child_count as usize;
                for &child in &children[..count] {
                    if self.env.events.get(child).is_some_and(|c| c.follows_parent && c.origin == slot + 1) {
                        self.env.queue(Work::Release { event: child, slot: slot + 1 });
                    }
                }
                match self.entry(slot, Callback::Release) {
                    Some(_) => {
                        let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Release));
                        ctx.event = event;
                        ctx.poly_row = Event::index(event) as u32;
                        ctx.forward = Forward::Release;
                        self.spawn_cb(engine, slot, Callback::Release, ctx);
                    }
                    None => self.env.queue(Work::Release { event, slot: slot + 1 }),
                }
            }
            Work::Controller { cc, value, slot } => {
                if slot >= slots {
                    return engine.controller(self.env.offset, cc, value);
                }
                self.write_sys(slot, SysArray::Cc, cc as usize, value);
                self.write_sys(slot, SysArray::CcTouched, cc as usize, 1);
                let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Controller));
                ctx.cc = i32::from(cc);
                ctx.value = value;
                ctx.forward = Forward::Controller;
                if !self.spawn_cb(engine, slot, Callback::Controller, ctx) {
                    self.write_sys(slot, SysArray::CcTouched, cc as usize, 0);
                    self.env.queue(Work::Controller { cc, value, slot: slot + 1 });
                }
            }
            Work::PolyAt { note, value, slot } => {
                if slot >= slots {
                    return;
                }
                self.write_sys(slot, SysArray::PolyAt, note as usize, value);
                let mut ctx = Ctx::new(slot, Kind::Cb(Callback::PolyAt));
                ctx.note = i32::from(note);
                ctx.value = value;
                ctx.forward = Forward::PolyAt;
                if !self.spawn_cb(engine, slot, Callback::PolyAt, ctx) {
                    self.env.queue(Work::PolyAt { note, value, slot: slot + 1 });
                }
            }
            Work::Rpn { nrpn, address, value, slot } => {
                if slot >= slots {
                    return;
                }
                let cb = if nrpn { Callback::Nrpn } else { Callback::Rpn };
                let mut ctx = Ctx::new(slot, Kind::Cb(cb));
                ctx.cc = address;
                ctx.value = value;
                ctx.forward = Forward::Rpn { nrpn };
                if !self.spawn_cb(engine, slot, cb, ctx) {
                    self.env.queue(Work::Rpn { nrpn, address, value, slot: slot + 1 });
                }
            }
        }
    }

    /// The event passed every slot: start it in the engine.
    fn play(&mut self, engine: &mut dyn KspEngine, event: i32) {
        let at = self.env.offset;
        let Some(e) = self.env.events.get_mut(event) else { return };
        e.at_engine = true;
        let spec = NoteSpec {
            event,
            note: e.note.clamp(0, 127) as u8,
            velocity: e.velocity.clamp(1, 127) as u8,
            sample_offset_us: e.sample_offset_us,
            length: e.length,
            volume_mdb: e.volume,
            tune_mc: e.tune,
            pan: e.pan,
            zone: e.zone,
            groups: &e.groups,
        };
        let voice = engine.play_note(at, &spec);
        e.voice = voice;
        if let (Some(v), true) = (voice, e.fade_in_us > 0) {
            engine.fade(at, v, Fade::In { duration_us: e.fade_in_us });
        }
        if e.length == NoteLength::Sample {
            self.env.events.free(event);
        }
    }

    fn write_sys(&mut self, slot: u8, a: SysArray, i: usize, value: i32) {
        let (prog, state) = (&self.programs[slot as usize], &mut self.states[slot as usize]);
        if let Some(v) = prog.sys_arrays[a as usize] {
            state.mem.ints[prog.vars[v as usize].slot as usize + i] = value;
        }
    }

    fn set_sys(&mut self, a: SysArray, i: usize, value: i32) {
        for slot in 0..self.programs.len() as u8 {
            self.write_sys(slot, a, i, value);
        }
    }

    /// Start a callback if the slot defines it. Returns whether it ran.
    fn spawn_cb(&mut self, engine: &mut dyn KspEngine, slot: u8, cb: Callback, ctx: Ctx) -> bool {
        match self.entry(slot, cb) {
            Some(entry) => {
                self.spawn(engine, entry, ctx);
                true
            }
            None => false,
        }
    }

    fn spawn(&mut self, engine: &mut dyn KspEngine, entry: u32, mut ctx: Ctx) {
        let Some(i) = self.free_threads.pop() else {
            self.env.note("KSP callback pool exhausted; callback dropped");
            self.forward(ctx);
            return;
        };
        self.env.next_callback_id = self.env.next_callback_id % i32::MAX + 1;
        ctx.callback_id = self.env.next_callback_id;
        if !matches!(ctx.kind, Kind::Cb(Callback::Note | Callback::Release)) {
            ctx.poly_row = POLY_ROWS - 1;
        }
        let t = &mut self.threads[i as usize];
        *t = Thread { pc: entry, live: true, generation: t.generation.wrapping_add(1), ctx, ..Thread::default() };
        self.resume(engine, i);
    }

    fn resume(&mut self, engine: &mut dyn KspEngine, i: u16) {
        let t = &mut self.threads[i as usize];
        let slot = t.ctx.slot as usize;
        let budget = self.env.block_fuel.min(CALLBACK_FUEL);
        let mut fuel = budget;
        let result = vm::exec(
            &mut Machine {
                prog: &self.programs[slot],
                slot: &mut self.states[slot],
                env: &mut self.env,
                stk: &mut self.stacks,
                engine,
                t,
            },
            &mut fuel,
        );
        self.env.block_fuel -= budget - fuel;
        match result {
            Ok(Yield::Done) => self.finish(i),
            Ok(Yield::Wait(at)) => {
                let t = &mut self.threads[i as usize];
                t.waiting = true;
                let generation = t.generation;
                self.env.timer(at, TimerKind::Resume { thread: i, generation });
                self.yielded(i);
            }
            Ok(Yield::OutOfFuel) if budget == CALLBACK_FUEL => {
                let pc = self.threads[i as usize].pc;
                self.env.fault(slot as u8, pc, "KSP callback exceeded its instruction budget");
                self.finish(i);
            }
            Ok(Yield::OutOfFuel) => {
                // Block budget spent: continue at the start of the next block.
                let generation = self.threads[i as usize].generation;
                let at = self.env.clock();
                self.env.timer(at, TimerKind::Resume { thread: i, generation });
            }
            Err(f) => {
                let pc = self.threads[i as usize].pc;
                self.env.fault(slot as u8, pc, f.0);
                self.finish(i);
            }
        }
    }

    fn finish(&mut self, i: u16) {
        self.yielded(i);
        let t = &mut self.threads[i as usize];
        t.live = false;
        t.generation = t.generation.wrapping_add(1);
        self.free_threads.push(i);
    }

    /// First yield of a callback: pass its event on unless the script ignored it.
    fn yielded(&mut self, i: u16) {
        let ctx = self.threads[i as usize].ctx;
        self.threads[i as usize].ctx.forward = Forward::None;
        self.forward(ctx);
    }

    fn forward(&mut self, ctx: Ctx) {
        let next = ctx.slot + 1;
        match ctx.forward {
            Forward::None => {}
            Forward::Note => {
                let Some(e) = self.env.events.get_mut(ctx.event) else { return };
                if std::mem::take(&mut e.ignored) {
                    if e.length == NoteLength::Sample {
                        self.env.events.free(ctx.event);
                    }
                } else {
                    self.env.queue(Work::Note { event: ctx.event, slot: next });
                }
            }
            Forward::Release => {
                let Some(e) = self.env.events.get_mut(ctx.event) else { return };
                if !std::mem::take(&mut e.release_ignored) {
                    self.env.queue(Work::Release { event: ctx.event, slot: next });
                }
            }
            Forward::Controller => {
                let cc = ctx.cc as u8;
                self.write_sys(ctx.slot, SysArray::CcTouched, cc as usize, 0);
                if !ctx.ignore_controller {
                    self.env.queue(Work::Controller { cc, value: ctx.value, slot: next });
                }
            }
            Forward::PolyAt => {
                if !ctx.ignore_controller {
                    self.env.queue(Work::PolyAt { note: ctx.note as u8, value: ctx.value, slot: next });
                }
            }
            Forward::Rpn { nrpn } => {
                if !ctx.ignore_controller {
                    self.env.queue(Work::Rpn { nrpn, address: ctx.cc, value: ctx.value, slot: next });
                }
            }
        }
    }
}

pub fn read_value(mem: &vm::Memory, var: &compile::Var) -> Value {
    let s = var.slot as usize;
    match (var.ty, var.len, var.poly) {
        (_, _, true) => Value::Int(0),
        (Ty::Int, None, _) => Value::Int(mem.ints[s]),
        (Ty::Real, None, _) => Value::Real(mem.reals[s]),
        (Ty::Str, None, _) => Value::Text(mem.strs[s].clone()),
        (Ty::Int, Some(n), _) => Value::Array(mem.ints[s..s + n as usize].iter().map(|&x| Value::Int(x)).collect()),
        (Ty::Real, Some(n), _) => Value::Array(mem.reals[s..s + n as usize].iter().map(|&x| Value::Real(x)).collect()),
        (Ty::Str, Some(n), _) => Value::Array(mem.strs[s..s + n as usize].iter().map(|x| Value::Text(x.clone())).collect()),
    }
}

/// Write a saved value back; mismatched types or lengths are ignored element-wise.
pub fn write_value(mem: &mut vm::Memory, var: &compile::Var, value: &Value) {
    if var.poly {
        return;
    }
    let s = var.slot as usize;
    let one = |mem: &mut vm::Memory, i: usize, v: &Value| match (var.ty, v) {
        (Ty::Int, Value::Int(n)) => mem.ints[i] = *n,
        (Ty::Real, Value::Real(n)) => mem.reals[i] = *n,
        (Ty::Str, Value::Text(t)) => {
            mem.strs[i].clear();
            mem.strs[i].push_str(t);
        }
        _ => {}
    };
    match (var.len, value) {
        (None, v) => one(mem, s, v),
        (Some(n), Value::Array(items)) => {
            for (i, v) in items.iter().take(n as usize).enumerate() {
                one(mem, s + i, v);
            }
        }
        _ => {}
    }
}
