//! The KSP runtime: script slots, note events, callback scheduling and the engine
//! boundary. Everything reachable from MIDI input and `process` is preallocated;
//! steady-state event handling neither allocates nor locks.
//!
//! Events flow slot by slot. A note, release or controller event runs the matching
//! callback in slot N; unless the callback ignores it, the event moves to slot N+1
//! when the callback first yields (finishes or waits). After the last slot it
//! reaches the engine. Notes generated by `play_note` in slot N start at N+1.

use super::builtins::{self as b, CC_SLOTS, SysArray};
use super::compile::{self, Callback, Program, Setup, Ty, VarId};
use super::engine::{EnginePar, EventId, Fade, GroupMask, KspEngine, NoteLength, NoteSpec};
use super::vm::{self, Ctx, Forward, Kind, Machine, POLY_ROWS, SlotState, Stacks, Thread, Yield};
use super::{HostState, Interface, KeyState, Value};
use anyhow::{Result, bail};
use std::cmp::Reverse;
use std::collections::{BTreeMap, BinaryHeap, VecDeque};
use std::sync::{Arc, Mutex, Weak};

/// `source` compiled for `setup`, one copy per process while any runtime
/// holds it: parts and plugin instances playing one instrument run the same
/// code over their own memory.
fn compiled(source: &str, setup: &Setup) -> Result<Arc<Program>> {
    type Compiled = std::collections::HashMap<(Box<str>, usize, usize), Weak<Program>>;
    static COMPILED: Mutex<Option<Compiled>> = Mutex::new(None);
    let lock = || COMPILED.lock().unwrap_or_else(|e| e.into_inner());
    let key = (Box::from(source), setup.groups, setup.outputs);
    if let Some(p) = lock().get_or_insert_default().get(&key).and_then(Weak::upgrade) {
        return Ok(p);
    }
    let program = Arc::new(compile::compile(source, setup)?);
    let mut compiled = lock();
    let compiled = compiled.get_or_insert_default();
    compiled.retain(|_, p| p.strong_count() > 0);
    compiled.insert(key, Arc::downgrade(&program));
    Ok(program)
}

pub const MAX_SLOTS: usize = 5;
pub const EVENT_CAPACITY: usize = 4096;
const EVENT_INDEX_BITS: u32 = 12;
const MAX_CHILDREN: usize = 8;
const THREAD_CAPACITY: usize = 1024;
const TIMER_CAPACITY: usize = 8192;
const WORK_CAPACITY: usize = 4096;
const FAULT_CAPACITY: usize = 256;
/// Distinct service notes kept; each is static text.
const NOTE_CAPACITY: usize = 64;
/// Minimum free bytes a snapshot string starts with.
const SNAPSHOT_SLACK: usize = 64;
/// Stored engine parameters that may be added after `on init` without allocating.
const ENGINE_PAR_HEADROOM: usize = 1024;
/// Instructions one callback may run between waits.
pub const CALLBACK_FUEL: u64 = 5_000_000;
/// Instructions all callbacks together may run per frame of an audio block
/// (about 2 ns each, so under half the block's time); the rest is deferred.
pub const FUEL_PER_FRAME: u64 = 4_096;
/// Budget for the first block, and the floor for tiny ones.
pub const BLOCK_FUEL: u64 = 512 * FUEL_PER_FRAME;
/// `on async_complete` callbacks one settle delivers; the rest wait a block.
const MAX_COMPLETIONS: u32 = 64;
/// `on init` runs off the audio thread and may do far more work.
pub const INIT_FUEL: u64 = 1_000_000_000;

/// Saved values of persistent variables, per script slot, keyed by variable name.
pub type Persisted = BTreeMap<String, Value>;

/// What the host shows of running scripts, refreshed in place by
/// [`Runtime::refresh_live`].
#[derive(Clone, Debug, PartialEq)]
pub struct Live {
    /// Script slot of `interface`: the last slot with a performance view.
    pub slot: usize,
    pub interface: Option<Interface>,
    /// Every key; unset names and colors are empty.
    pub keys: BTreeMap<u8, KeyState>,
}

#[derive(Clone, Copy, Debug)]
pub struct Event {
    generation: u16,
    pub live: bool,
    pub note: i32,
    pub velocity: i32,
    pub pars: [i32; 4],
    pub volume: i32,
    pub tune: i32,
    pub pan: i32,
    pub zone: i32,
    pub sample_offset_us: i64,
    pub length: NoteLength,
    pub groups: GroupMask,
    pub marks: u32,
    /// -1 for MIDI, otherwise the generating slot.
    pub source: i32,
    /// First slot that sees this event.
    pub origin: u8,
    /// Slots that have run (or skipped) this note, i.e. the next slot index.
    pub reached: u8,
    /// Slots whose release processing has started, as a bitmask.
    pub released: u8,
    pub parent: i32,
    pub children: [i32; MAX_CHILDREN],
    pub child_count: u8,
    /// `play_note(..., -1)`: released with its parent.
    pub follows_parent: bool,
    pub ignored: bool,
    pub release_ignored: bool,
    pub at_engine: bool,
    pub voice: Option<EventId>,
    /// MIDI key still down.
    pub held: bool,
    pub fade_in_us: i32,
}

impl Event {
    const EMPTY: Self = Self {
        generation: 0,
        live: false,
        note: 0,
        velocity: 0,
        pars: [0; 4],
        volume: 0,
        tune: 0,
        pan: 0,
        zone: -1,
        sample_offset_us: 0,
        length: NoteLength::UntilNoteOff,
        groups: GroupMask::all(),
        marks: 0,
        source: -1,
        origin: 0,
        reached: 0,
        released: 0,
        parent: 0,
        children: [0; MAX_CHILDREN],
        child_count: 0,
        follows_parent: false,
        ignored: false,
        release_ignored: false,
        at_engine: false,
        voice: None,
        held: false,
        fade_in_us: 0,
    };

    pub fn index(id: i32) -> usize {
        (id as u32 & ((1 << EVENT_INDEX_BITS) - 1)) as usize
    }

    /// The event as the engine sees it; `id` is its KSP event ID.
    fn spec(&self, id: i32) -> NoteSpec<'_> {
        NoteSpec {
            event: id,
            note: self.note.clamp(0, 127) as u8,
            velocity: self.velocity.clamp(1, 127) as u8,
            sample_offset_us: self.sample_offset_us,
            length: self.length,
            volume_mdb: self.volume,
            tune_mc: self.tune,
            pan: self.pan,
            zone: self.zone,
            groups: &self.groups,
        }
    }
}

/// Fixed pool of events. Freed events stay addressable until their slot is reused
/// (FIFO), so late `note_off`/`fade_out` calls on finished notes still resolve.
pub struct Events {
    slots: Vec<Event>,
    free: VecDeque<u32>,
}

impl Events {
    fn new() -> Self {
        Self {
            slots: vec![Event::EMPTY; EVENT_CAPACITY],
            free: (0..EVENT_CAPACITY as u32).collect(),
        }
    }

    fn alloc(&mut self) -> Option<i32> {
        let i = match self.free.pop_front() {
            Some(i) => i,
            // ponytail: linear scan, only when the pool is full. Sample-length notes stay
            // live until released because the engine does not report voice ends.
            None => {
                let i = self
                    .slots
                    .iter()
                    .position(|e| e.live && e.at_engine && e.length == NoteLength::Sample)?;
                i as u32
            }
        };
        let e = &mut self.slots[i as usize];
        let generation = e.generation % 0x7FFF + 1;
        *e = Event {
            generation,
            live: true,
            ..Event::EMPTY
        };
        Some(i32::from(generation) << EVENT_INDEX_BITS | i as i32)
    }

    pub fn get(&self, id: i32) -> Option<&Event> {
        let e = self.slots.get(Event::index(id))?;
        (id > 0 && i32::from(e.generation) == id >> EVENT_INDEX_BITS).then_some(e)
    }

    pub fn get_mut(&mut self, id: i32) -> Option<&mut Event> {
        let e = self.slots.get_mut(Event::index(id))?;
        (id > 0 && i32::from(e.generation) == id >> EVENT_INDEX_BITS).then_some(e)
    }

    fn free(&mut self, id: i32) {
        if let Some(e) = self.get_mut(id).filter(|e| e.live) {
            e.live = false;
            self.free.push_back(Event::index(id) as u32);
        }
    }

    /// Whether the key behind this event (or its ancestors) is still down.
    pub fn held(&self, mut id: i32) -> bool {
        for _ in 0..8 {
            let Some(e) = self.get(id) else { return false };
            if e.source < 0 {
                return e.held;
            }
            id = e.parent;
        }
        false
    }

    /// Live event IDs addressed by a plain ID, `by_marks` value or `$ALL_EVENTS`.
    pub fn targets(&self, id: i32, out: &mut Vec<i32>) {
        out.clear();
        if id == b::ALL_EVENTS || (id & b::MARKS_FLAG != 0 && id > 0) {
            let marks = (id & !b::MARKS_FLAG) as u32;
            for (i, e) in self.slots.iter().enumerate() {
                if e.live && (id == b::ALL_EVENTS || e.marks & marks != 0) {
                    out.push(i32::from(e.generation) << EVENT_INDEX_BITS | i as i32);
                }
            }
        } else if self.get(id).is_some() {
            out.push(id);
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub enum Work {
    Note {
        event: i32,
        slot: u8,
    },
    Release {
        event: i32,
        slot: u8,
    },
    Controller {
        cc: u8,
        value: i32,
        slot: u8,
    },
    PolyAt {
        note: u8,
        value: i32,
        slot: u8,
    },
    Rpn {
        nrpn: bool,
        address: i32,
        value: i32,
        slot: u8,
    },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum TimerKind {
    Resume { thread: u16, generation: u32 },
    Release { event: i32, slot: u8 },
    Listener { slot: u8, generation: u32 },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Timer {
    at: u64,
    seq: u64,
    kind: TimerKind,
}

#[derive(Clone, Copy, Debug)]
struct FaultRecord {
    slot: u8,
    pc: u32,
    what: &'static str,
    count: u32,
}

/// Live MIDI state shared by all slots.
pub struct Input {
    pub cc: [i32; CC_SLOTS],
    pub pitch_bend: i32,
    /// MIDI events per key, newest last; zero marks an empty entry.
    keys: [[i32; 4]; 128],
}

/// Shared runtime state visible to builtins.
pub struct Env {
    pub host: HostState,
    pub events: Events,
    pub input: Input,
    pub work: VecDeque<Work>,
    timers: BinaryHeap<Reverse<Timer>>,
    timer_seq: u64,
    /// Sample time at the start of the current block, and the offset within it.
    pub now: u64,
    pub offset: u32,
    pub sample_rate: f64,
    pub tempo: f64,
    pub transport: bool,
    pub timer_origin: u64,
    pub block_fuel: u64,
    pub targets: Vec<i32>,
    pub message: String,
    /// Engine parameters the engine does not model, sorted by address.
    engine_pars: Vec<(EnginePar, i32)>,
    /// Set while `on init` runs off the audio thread: storage may grow.
    loading: bool,
    pub saved_arrays: BTreeMap<(u8, VarId), Value>,
    pub persisted: Vec<Persisted>,
    /// Distinct service notes, preallocated so noting never allocates.
    pub notes: Vec<&'static str>,
    faults: Vec<FaultRecord>,
    rng: u64,
    next_callback_id: i32,
    next_async_id: i32,
    pub async_done: Vec<(u8, i32, i32)>,
    pub stop_waits: Vec<(i32, i32)>,
    pub listeners_changed: u8,
    pub pgs_changed: bool,
    /// Time Machine Pro voice limits, standard and HQ (Kontakt's defaults).
    pub voice_limits: [i32; 2],
}

impl Env {
    fn new(host: HostState, persisted: Vec<Persisted>) -> Self {
        Self {
            host,
            events: Events::new(),
            input: Input {
                cc: [0; CC_SLOTS],
                pitch_bend: 0,
                keys: [[0; 4]; 128],
            },
            work: VecDeque::with_capacity(WORK_CAPACITY),
            timers: BinaryHeap::with_capacity(TIMER_CAPACITY),
            timer_seq: 0,
            now: 0,
            offset: 0,
            sample_rate: 48_000.0,
            tempo: 120.0,
            transport: false,
            timer_origin: 0,
            block_fuel: BLOCK_FUEL,
            targets: Vec::with_capacity(EVENT_CAPACITY),
            message: String::with_capacity(256),
            engine_pars: Vec::with_capacity(ENGINE_PAR_HEADROOM),
            loading: false,
            saved_arrays: BTreeMap::new(),
            persisted,
            notes: Vec::with_capacity(NOTE_CAPACITY),
            faults: Vec::with_capacity(FAULT_CAPACITY),
            rng: 0x9E37_79B9_7F4A_7C15,
            next_callback_id: 0,
            next_async_id: 0,
            async_done: Vec::with_capacity(64),
            stop_waits: Vec::with_capacity(64),
            listeners_changed: 0,
            pgs_changed: false,
            voice_limits: [8, 2],
        }
    }

    /// Absolute sample time of the executing callback.
    pub fn clock(&self) -> u64 {
        self.now + u64::from(self.offset)
    }

    pub fn micros(&self, samples: u64) -> i64 {
        (samples as f64 * 1e6 / self.sample_rate) as i64
    }

    pub fn samples(&self, us: i64) -> u64 {
        (us.max(0) as f64 * self.sample_rate / 1e6).round() as u64
    }

    pub fn engine_par(&self, par: EnginePar) -> Option<i32> {
        let i = self.engine_pars.binary_search_by_key(&par, |e| e.0).ok()?;
        Some(self.engine_pars[i].1)
    }

    /// Store a parameter the engine does not model. After loading, new
    /// addresses only fit the preallocated headroom.
    pub fn set_engine_par(&mut self, par: EnginePar, value: i32) {
        match self.engine_pars.binary_search_by_key(&par, |e| e.0) {
            Ok(i) => self.engine_pars[i].1 = value,
            Err(_) if !self.loading && self.engine_pars.len() == self.engine_pars.capacity() => {
                self.note("set_engine_par: parameter store full; value dropped");
            }
            Err(i) => self.engine_pars.insert(i, (par, value)),
        }
    }

    pub fn quarter_us(&self) -> i32 {
        (60e6 / self.tempo) as i32
    }

    pub fn note(&mut self, text: &'static str) {
        if self.notes.len() < NOTE_CAPACITY && !self.notes.contains(&text) {
            self.notes.push(text);
        }
    }

    pub fn random(&mut self, lo: i32, hi: i32) -> i32 {
        self.rng ^= self.rng << 13;
        self.rng ^= self.rng >> 7;
        self.rng ^= self.rng << 17;
        let (lo, hi) = (lo.min(hi) as i64, lo.max(hi) as i64);
        (lo + (self.rng % (hi - lo + 1) as u64) as i64) as i32
    }

    pub fn next_async(&mut self) -> i32 {
        self.next_async_id = self.next_async_id % i32::MAX + 1;
        self.next_async_id
    }

    pub fn queue(&mut self, w: Work) {
        if self.work.len() < WORK_CAPACITY {
            self.work.push_back(w);
        } else {
            self.note("KSP event queue full; event dropped");
        }
    }

    fn timer(&mut self, at: u64, kind: TimerKind) {
        if self.timers.len() >= TIMER_CAPACITY {
            self.note("KSP timer queue full; wait dropped");
            return;
        }
        self.timer_seq += 1;
        self.timers.push(Reverse(Timer {
            at,
            seq: self.timer_seq,
            kind,
        }));
    }

    pub fn release_after(&mut self, event: i32, slot: u8, us: i64) {
        let at = self.clock() + self.samples(us).max(1);
        self.timer(at, TimerKind::Release { event, slot });
    }

    pub fn fault(&mut self, slot: u8, pc: u32, what: &'static str) {
        if let Some(f) = self
            .faults
            .iter_mut()
            .find(|f| f.slot == slot && f.pc == pc && f.what == what)
        {
            f.count = f.count.saturating_add(1);
        } else if self.faults.len() < FAULT_CAPACITY {
            self.faults.push(FaultRecord {
                slot,
                pc,
                what,
                count: 1,
            });
        }
    }

    /// Create a note event for `play_note` in `slot`, queued for the next slot.
    pub fn play_note(
        &mut self,
        slot: u8,
        parent: i32,
        note: i32,
        velocity: i32,
        offset_us: i32,
        duration_us: i32,
    ) -> i32 {
        let Some(id) = self.events.alloc() else {
            self.note("KSP event pool exhausted; play_note ignored");
            return 0;
        };
        let parent_state = self
            .events
            .get(parent)
            .map(|p| (p.groups, p.released & (1 << slot) != 0));
        let e = self.events.get_mut(id).expect("fresh event");
        e.note = note;
        e.velocity = velocity;
        e.sample_offset_us = i64::from(offset_us);
        e.source = i32::from(slot);
        e.origin = slot + 1;
        e.reached = slot + 1;
        e.parent = parent;
        e.length = if duration_us == 0 {
            NoteLength::Sample
        } else {
            NoteLength::UntilNoteOff
        };
        e.follows_parent = duration_us < 0 && parent_state.is_some();
        if let Some((groups, _)) = parent_state {
            e.groups = groups;
        }
        self.queue(Work::Note {
            event: id,
            slot: slot + 1,
        });
        match parent_state {
            Some((_, true)) if duration_us < 0 => self.queue(Work::Release {
                event: id,
                slot: slot + 1,
            }),
            Some(_) if duration_us < 0 => {
                if let Some(p) = self.events.get_mut(parent) {
                    if (p.child_count as usize) < MAX_CHILDREN {
                        p.children[p.child_count as usize] = id;
                        p.child_count += 1;
                    } else {
                        self.note(
                            "Too many notes follow one parent; extra notes release after 1 s",
                        );
                        self.release_after(id, slot + 1, 1_000_000);
                    }
                }
            }
            _ if duration_us > 0 => self.release_after(id, slot + 1, i64::from(duration_us)),
            _ => {}
        }
        id
    }

    /// Stop a note from `slot` downstream: its release starts after the caller.
    pub fn note_off(&mut self, slot: u8, id: i32) {
        if let Some(e) = self.events.get(id) {
            let start = (slot + 1).max(e.origin);
            self.queue(Work::Release {
                event: id,
                slot: start,
            });
        }
    }
}

pub struct Runtime {
    /// Compiled code, shared with every runtime that compiled the same
    /// script (see [`compiled`]).
    programs: Vec<Arc<Program>>,
    states: Vec<SlotState>,
    pub env: Env,
    stacks: Stacks,
    threads: Vec<Thread>,
    free_threads: Vec<u16>,
    outputs: usize,
    /// Per-callback instruction cap: `CALLBACK_FUEL`, or `INIT_FUEL` while loading.
    fuel_cap: u64,
    /// Engine parameters `on init` set through an engine that accepted them
    /// before any sound engine existed (in call order); the playing engine
    /// applies them when the runtime is installed.
    pub init_engine_pars: Vec<(EnginePar, i32)>,
    /// Controllers the scripts set while loading (`set_controller` in
    /// `on init` or `on persistence_changed`), in call order.
    /// The playing engine applies them on install and after a reset.
    pub init_controllers: Vec<(u8, u8)>,
    /// Counts script runs and host writes to script memory; see [`changes`](Self::changes).
    changes: u64,
}

impl Runtime {
    /// Grows whenever script memory may have changed: a callback ran or the
    /// host wrote a variable. Equal counts mean equal memory, so refreshes
    /// can be skipped.
    pub fn changes(&self) -> u64 {
        self.changes
    }

    pub fn new(host: HostState, outputs: usize, persisted: Vec<Persisted>) -> Self {
        Self {
            programs: Vec::new(),
            states: Vec::new(),
            env: Env::new(host, persisted),
            stacks: Stacks::with_capacity(1024),
            threads: vec![Thread::default(); THREAD_CAPACITY],
            free_threads: (0..THREAD_CAPACITY as u16).rev().collect(),
            outputs,
            changes: 0,
            fuel_cap: CALLBACK_FUEL,
            init_engine_pars: Vec::new(),
            init_controllers: Vec::new(),
        }
    }

    /// Build a runtime from an instrument's scripts. Slots that fail stay present but
    /// disabled (events pass through them); their errors are returned per slot.
    pub fn with_scripts(
        scripts: &[impl AsRef<str>],
        engine: &mut dyn KspEngine,
        outputs: usize,
        persisted: Vec<Persisted>,
    ) -> (Self, Vec<Option<String>>) {
        let mut rt = Self::new(HostState::default(), outputs, persisted);
        let errors = scripts
            .iter()
            .take(MAX_SLOTS)
            .map(|s| rt.load(engine, s.as_ref()).err().map(|e| format!("{e:#}")))
            .collect();
        (rt, errors)
    }

    pub fn slots(&self) -> usize {
        self.programs.len()
    }

    pub fn host(&self) -> &HostState {
        &self.env.host
    }

    pub fn into_host(self) -> HostState {
        self.env.host
    }

    pub fn now(&self) -> u64 {
        self.env.now
    }

    pub fn set_tempo(&mut self, bpm: f64) {
        if bpm.is_finite() && bpm > 0.0 {
            self.env.tempo = bpm;
        }
    }

    /// Sample rate for µs timing; the engine sets it when the host rate changes.
    pub fn set_sample_rate(&mut self, rate: f64) {
        if rate.is_finite() && rate > 0.0 {
            self.env.sample_rate = rate;
        }
    }

    /// Compile a script into the next slot and run `on init`, off the audio
    /// thread. Shared host state is committed only if initialization succeeds.
    pub fn load(&mut self, engine: &mut dyn KspEngine, source: &str) -> Result<()> {
        self.env.loading = true;
        let result = self.load_slot(engine, source);
        self.env.loading = false;
        self.env.engine_pars.reserve(ENGINE_PAR_HEADROOM);
        result
    }

    fn load_slot(&mut self, engine: &mut dyn KspEngine, source: &str) -> Result<()> {
        if self.programs.len() >= MAX_SLOTS {
            bail!("At most {MAX_SLOTS} script slots");
        }
        self.env.sample_rate = engine.sample_rate();
        let index = self.programs.len() as u8;
        let setup = Setup {
            groups: engine.group_count(),
            outputs: self.outputs,
        };
        let program = match compiled(source, &setup) {
            Ok(p) => p,
            Err(e) => {
                self.programs.push(Arc::default());
                let mut state = SlotState::new(index, &self.programs[index as usize]);
                state.error = Some(format!("{e:#}"));
                self.states.push(state);
                return Err(e);
            }
        };
        self.states.push(SlotState::new(index, &program));
        self.programs.push(program);
        let staged = self.env.host.clone();
        if let Err(e) = self.run_init(engine, index) {
            self.env.host = staged;
            self.states[index as usize].error = Some(format!("{e:#}"));
            return Err(e);
        }
        self.restore_persistent(index);
        // Loading is off the audio thread: callbacks it triggers get the init budget.
        let block_fuel = std::mem::replace(&mut self.env.block_fuel, INIT_FUEL);
        self.fuel_cap = INIT_FUEL;
        self.spawn_cb(
            engine,
            index,
            Callback::PersistenceChanged,
            Ctx::new(index, Kind::Cb(Callback::PersistenceChanged)),
        );
        self.settle(engine);
        self.fuel_cap = CALLBACK_FUEL;
        self.env.block_fuel = block_fuel;
        Ok(())
    }

    fn run_init(&mut self, engine: &mut dyn KspEngine, slot: u8) -> Result<()> {
        let prog = &self.programs[slot as usize];
        let entry = prog
            .callback(Callback::Init)
            .expect("compiler requires on init");
        let mut t = Thread {
            pc: entry,
            live: true,
            ctx: Ctx::new(slot, Kind::Cb(Callback::Init)),
            ..Thread::default()
        };
        t.ctx.poly_row = POLY_ROWS - 1;
        let mut fuel = INIT_FUEL;
        let saved_fuel = std::mem::replace(&mut self.env.block_fuel, INIT_FUEL);
        let result = vm::exec(
            &mut Machine {
                prog,
                slot: &mut self.states[slot as usize],
                env: &mut self.env,
                stk: &mut self.stacks,
                engine,
                t: &mut t,
            },
            &mut fuel,
        );
        self.env.block_fuel = saved_fuel;
        match result {
            Ok(Yield::Done) => {}
            Ok(Yield::Wait(_)) => bail!(
                "KSP line {}: wait() is not allowed in on init",
                prog.line(t.pc - 1)
            ),
            // Like Kontakt's runaway-loop guard, stop the callback, not the script:
            // everything `on init` declared before the loop stays usable.
            Ok(Yield::OutOfFuel) => self.env.fault(
                slot,
                t.pc,
                "on init exceeded its instruction budget and was stopped",
            ),
            Err(f) => bail!("KSP line {}: {}", prog.line(t.pc.saturating_sub(1)), f.0),
        }
        // Nothing plays yet, so init's notes are dropped; controllers it sets
        // settle with `on persistence_changed`.
        self.env
            .work
            .retain(|w| matches!(w, Work::Controller { .. }));
        Ok(())
    }

    fn restore_persistent(&mut self, slot: u8) {
        let Some(saved) = self.env.persisted.get(slot as usize) else {
            return;
        };
        let (prog, state) = (
            &self.programs[slot as usize],
            &mut self.states[slot as usize],
        );
        for &v in &state.persistent {
            let var = &prog.vars[v as usize];
            if let Some(value) = saved.get(&*var.name) {
                write_value(&mut state.mem, var, value);
            }
        }
    }

    /// Snapshot of persistent variables for every slot, for the host to save.
    pub fn persistence(&self) -> Vec<Persisted> {
        let mut saved: Vec<Persisted> = self
            .programs
            .iter()
            .zip(&self.states)
            .map(|(prog, state)| {
                state
                    .persistent
                    .iter()
                    .map(|&v| {
                        let var = &prog.vars[v as usize];
                        (var.name.to_string(), read_value(&state.mem, var))
                    })
                    .collect()
            })
            .collect();
        // Room for strings to grow before `refresh_persistence` must cut them.
        each_text(&mut saved, |t| t.reserve(t.len().max(SNAPSHOT_SLACK)));
        saved
    }

    /// Update `saved`, built earlier by [`persistence`](Self::persistence), in
    /// place without allocating, so the audio thread can refresh a snapshot
    /// the host then saves. A string that outgrew its buffer is cut to it;
    /// [`settle_persistence`] tells the host and makes room. Returns whether
    /// any value changed.
    pub fn refresh_persistence(&self, saved: &mut [Persisted]) -> bool {
        let mut at = Refresh::default();
        while !self.refresh_persistence_within(saved, &mut at, usize::MAX) {}
        at.changed
    }

    /// [`refresh_persistence`](Self::refresh_persistence) a piece at a time:
    /// about `budget` values from where `at` stands. True once `saved` is
    /// whole again; `at.changed` then says whether anything differed. Scripts
    /// keep megabytes of persistent tables, too much for one audio block.
    pub fn refresh_persistence_within(
        &self,
        saved: &mut [Persisted],
        at: &mut Refresh,
        budget: usize,
    ) -> bool {
        let mut left = budget;
        let slots = self.programs.len().min(self.states.len()).min(saved.len());
        while at.slot < slots {
            let (prog, state) = (&self.programs[at.slot], &self.states[at.slot]);
            while let Some(&v) = state.persistent.get(at.item) {
                if left == 0 {
                    return false;
                }
                let var = &prog.vars[v as usize];
                let len = if var.poly { 0 } else { var.len.map_or(1, |n| n as usize) };
                let end = len.min(at.at.saturating_add(left));
                if let Some(value) = saved[at.slot].get_mut(&*var.name) {
                    at.changed |= refresh_range(&state.mem, var, value, at.at..end);
                }
                left = left.saturating_sub(end - at.at + 1);
                if end < len {
                    at.at = end;
                } else {
                    (at.item, at.at) = (at.item + 1, 0);
                }
            }
            (at.slot, at.item) = (at.slot + 1, 0);
        }
        true
    }

    pub fn interface(&self, slot: usize) -> Interface {
        self.states[slot]
            .ui
            .interface(&self.programs[slot], &self.states[slot].mem)
    }

    /// What the host shows while the scripts run, shaped for
    /// [`refresh_live`](Self::refresh_live): every string has room to grow and
    /// every key has an entry.
    pub fn live(&self) -> Live {
        let slot = (0..self.states.len())
            .rev()
            .find(|&s| self.states[s].ui.performance);
        let mut interface = slot.map(|s| self.interface(s));
        for c in interface.iter_mut().flat_map(|i| &mut i.controls) {
            // Properties scripts often first set while running.
            for name in ["$CONTROL_PAR_TEXT", "$CONTROL_PAR_PICTURE"] {
                c.properties
                    .entry(name.into())
                    .or_insert_with(|| Value::Text(String::new()));
            }
            c.properties
                .entry("$CONTROL_PAR_PICTURE_STATE".into())
                .or_insert(Value::Int(0));
            for v in c.properties.values_mut() {
                each_text_in(v, &mut room);
            }
            c.menu.iter_mut().for_each(|(t, _)| room(t));
        }
        let text = || String::with_capacity(SNAPSHOT_SLACK);
        let keys = (0..128)
            .map(|n| {
                let key = KeyState {
                    name: text(),
                    color: Some(Value::Text(text())),
                    kind: Some(Value::Text(text())),
                    pressed: false,
                };
                (n, key)
            })
            .collect();
        let mut live = Live {
            slot: slot.unwrap_or(0),
            interface,
            keys,
        };
        self.refresh_live(&mut live);
        live
    }

    /// Copy control properties, values and keys into `live`, built by
    /// [`live`](Self::live), in place and without allocating, so the audio
    /// thread can refresh it for the host. Strings are cut to the room they
    /// have; properties and menu items `live` lacks are skipped.
    /// Returns whether anything changed.
    pub fn refresh_live(&self, live: &mut Live) -> bool {
        let mut at = Refresh::default();
        while !self.refresh_live_within(live, &mut at, usize::MAX) {}
        at.changed
    }

    /// [`refresh_live`](Self::refresh_live) a piece at a time, about `budget`
    /// control properties from where `at` stands; true once done.
    pub fn refresh_live_within(&self, live: &mut Live, at: &mut Refresh, budget: usize) -> bool {
        if let Some(out) = &mut live.interface
            && let Some(state) = self.states.get(live.slot)
            && at.item < out.controls.len()
        {
            let prog = &self.programs[live.slot];
            at.changed |= state.ui.refresh(prog, &state.mem, out, &mut at.item, budget);
            if at.item != usize::MAX {
                return false;
            }
        }
        for (note, key) in &mut live.keys {
            let host = self.env.host.keyboard.get(note);
            let mut changed = copy_text(&mut key.name, host.map_or("", |k| &k.name));
            fn text(v: Option<&Value>) -> &str {
                match v {
                    Some(Value::Text(s)) => s,
                    _ => "",
                }
            }
            if let Some(Value::Text(t)) = &mut key.color {
                changed |= copy_text(t, text(host.and_then(|k| k.color.as_ref())));
            }
            if let Some(Value::Text(t)) = &mut key.kind {
                changed |= copy_text(t, text(host.and_then(|k| k.kind.as_ref())));
            }
            let pressed = host.is_some_and(|k| k.pressed);
            changed |= key.pressed != pressed;
            key.pressed = pressed;
            at.changed |= changed;
        }
        true
    }

    /// Slot errors, runtime faults (with script line numbers) and service notes.
    pub fn diagnostics(&self) -> Vec<String> {
        let mut out: Vec<String> = self
            .states
            .iter()
            .enumerate()
            .filter_map(|(i, s)| s.error.as_ref().map(|e| format!("Slot {}: {e}", i + 1)))
            .collect();
        for (i, p) in self.programs.iter().enumerate() {
            out.extend(
                p.errors
                    .iter()
                    .map(|e| format!("Slot {}: callback disabled: {e}", i + 1)),
            );
        }
        out.extend(self.env.faults.iter().map(|f| {
            let line = self.programs[f.slot as usize].line(f.pc.saturating_sub(1));
            format!("Slot {} line {line}: {} ({}x)", f.slot + 1, f.what, f.count)
        }));
        out.extend(self.env.notes.iter().map(|n| n.to_string()));
        out
    }

    pub fn last_message(&self) -> &str {
        &self.env.message
    }

    // ---- Host input ------------------------------------------------------------------

    pub fn note_on(&mut self, engine: &mut dyn KspEngine, at: u32, note: u8, velocity: u8) {
        if velocity == 0 {
            return self.note_off(engine, at, note);
        }
        self.advance(engine, at);
        let note = note.min(127);
        self.set_sys(SysArray::KeyDown, note as usize, 1);
        let Some(id) = self.env.events.alloc() else {
            self.env.note("KSP event pool exhausted; note dropped");
            return;
        };
        let e = self.env.events.get_mut(id).expect("fresh event");
        e.note = i32::from(note);
        e.velocity = i32::from(velocity);
        e.held = true;
        let keys = &mut self.env.input.keys[note as usize];
        if let Some(free) = keys.iter_mut().find(|k| **k == 0) {
            *free = id;
        } else {
            keys.rotate_left(1);
            keys[3] = id;
        }
        self.env.queue(Work::Note { event: id, slot: 0 });
        self.settle(engine);
    }

    pub fn note_off(&mut self, engine: &mut dyn KspEngine, at: u32, note: u8) {
        self.advance(engine, at);
        let note = note.min(127);
        self.set_sys(SysArray::KeyDown, note as usize, 0);
        let keys = std::mem::take(&mut self.env.input.keys[note as usize]);
        for id in keys.into_iter().filter(|&id| id != 0) {
            if let Some(e) = self.env.events.get_mut(id) {
                e.held = false;
                self.env.queue(Work::Release { event: id, slot: 0 });
            }
        }
        self.settle(engine);
    }

    /// Controller 0..127; use `pitch_bend`/`channel_pressure` for the virtual ones.
    pub fn controller(&mut self, engine: &mut dyn KspEngine, at: u32, cc: u8, value: u8) {
        self.cc(engine, at, cc.min(127), i32::from(value));
    }

    /// Pitch bend, -8192..8191.
    pub fn pitch_bend(&mut self, engine: &mut dyn KspEngine, at: u32, value: i32) {
        self.env.input.pitch_bend = value.clamp(-8192, 8191);
        self.cc(
            engine,
            at,
            b::VCC_PITCH_BEND as u8,
            value.clamp(-8192, 8191),
        );
    }

    pub fn channel_pressure(&mut self, engine: &mut dyn KspEngine, at: u32, value: u8) {
        self.cc(engine, at, b::VCC_MONO_AT as u8, i32::from(value));
    }

    fn cc(&mut self, engine: &mut dyn KspEngine, at: u32, cc: u8, value: i32) {
        self.advance(engine, at);
        self.env.input.cc[cc as usize] = value;
        self.env.queue(Work::Controller { cc, value, slot: 0 });
        self.settle(engine);
    }

    pub fn poly_pressure(&mut self, engine: &mut dyn KspEngine, at: u32, note: u8, value: u8) {
        self.advance(engine, at);
        self.env.queue(Work::PolyAt {
            note: note.min(127),
            value: i32::from(value),
            slot: 0,
        });
        self.settle(engine);
    }

    pub fn rpn(
        &mut self,
        engine: &mut dyn KspEngine,
        at: u32,
        nrpn: bool,
        address: u16,
        value: u16,
    ) {
        self.advance(engine, at);
        self.env.queue(Work::Rpn {
            nrpn,
            address: i32::from(address),
            value: i32::from(value),
            slot: 0,
        });
        self.settle(engine);
    }

    /// A host-side edit of control `control` (index into `Interface::controls`).
    pub fn ui_control(
        &mut self,
        engine: &mut dyn KspEngine,
        slot: usize,
        control: usize,
        value: i32,
    ) {
        let Some(state) = self.states.get_mut(slot) else {
            return;
        };
        let Some(c) = state.ui.controls.get(control) else {
            return;
        };
        let v = c.var;
        // Host values (automation, articulations) stay within the control's range.
        let range = |p| match c.get(p) {
            Some(super::ui::Prop::Int(n)) => Some(*n),
            _ => None,
        };
        let value = match (range(b::CONTROL_PAR_MIN_VALUE), range(b::CONTROL_PAR_MAX_VALUE)) {
            (Some(a), Some(z)) => value.clamp(a.min(z), a.max(z)),
            _ => value,
        };
        let prog = self.programs[slot].clone();
        let var = &prog.vars[v as usize];
        if var.ty == Ty::Int && var.len.is_none() {
            state.mem.ints[var.slot as usize] = value;
            self.changes += 1;
        }
        // Kontakt runs the global `on ui_controls` first, then the control's own.
        let mut ctx = Ctx::new(slot as u8, Kind::UiControl);
        ctx.value = state.ui.var_id(v);
        if let Some(entry) = prog.callback(Callback::UiControls) {
            let mut ctx = ctx;
            ctx.kind = Kind::Cb(Callback::UiControls);
            self.spawn(engine, entry, ctx);
        }
        if let Some(entry) = prog.ui_callbacks[v as usize] {
            self.spawn(engine, entry, ctx);
        }
        self.spawn_cb(
            engine,
            slot as u8,
            Callback::UiUpdate,
            Ctx::new(slot as u8, Kind::Cb(Callback::UiUpdate)),
        );
        self.settle(engine);
    }

    pub fn set_transport(&mut self, engine: &mut dyn KspEngine, playing: bool) {
        if self.env.transport == playing {
            return;
        }
        self.env.transport = playing;
        let signal = if playing {
            b::signal::TRANSP_START
        } else {
            b::signal::TRANSP_STOP
        };
        for slot in 0..self.states.len() as u8 {
            if self.states[slot as usize].listener.transport {
                let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Listener));
                ctx.signal = signal;
                self.spawn_cb(engine, slot, Callback::Listener, ctx);
            }
        }
        self.settle(engine);
    }

    /// Finish the current block: resume every callback due before its end.
    pub fn process(&mut self, engine: &mut dyn KspEngine, frames: u32) {
        let end = self.env.now + u64::from(frames);
        // What the last settle left for later (see `settle`).
        if self.env.pgs_changed || !self.env.async_done.is_empty() {
            self.settle(engine);
        }
        self.run_timers(engine, end);
        if self.env.block_fuel == 0 {
            self.env
                .note("KSP instruction budget exhausted for a block; callbacks deferred");
        }
        self.env.now = end;
        self.env.offset = 0;
        // The next block is likely this size; its budget scales with its time.
        self.env.block_fuel = (u64::from(frames) * FUEL_PER_FRAME).max(BLOCK_FUEL / 8);
    }

    fn advance(&mut self, engine: &mut dyn KspEngine, at: u32) {
        self.run_timers(engine, self.env.now + u64::from(at));
        self.env.offset = at;
    }

    fn run_timers(&mut self, engine: &mut dyn KspEngine, until: u64) {
        while let Some(&Reverse(t)) = self.env.timers.peek() {
            if t.at >= until || self.env.block_fuel == 0 {
                break;
            }
            self.env.timers.pop();
            self.env.offset = t.at.saturating_sub(self.env.now) as u32;
            match t.kind {
                TimerKind::Resume { thread, generation } => {
                    let th = &mut self.threads[thread as usize];
                    if th.live && th.generation == generation {
                        th.waiting = false;
                        self.resume(engine, thread);
                    }
                }
                TimerKind::Release { event, slot } => self.env.queue(Work::Release { event, slot }),
                TimerKind::Listener { slot, generation } => {
                    let l = self.states[slot as usize].listener;
                    if l.generation == generation {
                        let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Listener));
                        ctx.signal = if l.timer_us > 0 {
                            b::signal::TIMER_MS
                        } else {
                            b::signal::TIMER_BEAT
                        };
                        self.spawn_cb(engine, slot, Callback::Listener, ctx);
                        self.schedule_listener(slot, t.at);
                    }
                }
            }
            self.settle(engine);
        }
    }

    fn schedule_listener(&mut self, slot: u8, from: u64) {
        let l = self.states[slot as usize].listener;
        let us = if l.timer_us > 0 {
            i64::from(l.timer_us)
        } else if l.beats > 0 {
            i64::from(self.env.quarter_us() / l.beats)
        } else {
            return;
        };
        let at = from + self.env.samples(us).max(1);
        self.env.timer(
            at,
            TimerKind::Listener {
                slot,
                generation: l.generation,
            },
        );
    }

    // ---- Scheduling ------------------------------------------------------------------

    /// Drain queued work and the follow-up callbacks it triggers.
    fn settle(&mut self, engine: &mut dyn KspEngine) {
        // `on pgs_changed` runs once per settle: scripts that answer a change
        // with another change would otherwise ping-pong here forever. Later
        // changes are delivered by the next settle.
        let mut pgs_delivered = false;
        // Likewise for scripts that answer every completion with a new
        // asynchronous call (a retry that can never succeed here).
        let mut completions = 0;
        loop {
            while let Some(w) = self.env.work.pop_front() {
                self.handle(engine, w);
            }
            if !self.env.stop_waits.is_empty() {
                self.stop_waits(engine);
                continue;
            }
            if self.env.listeners_changed != 0 {
                let changed = std::mem::take(&mut self.env.listeners_changed);
                for slot in 0..self.states.len() as u8 {
                    if changed & (1 << slot) != 0 {
                        self.schedule_listener(slot, self.env.clock());
                    }
                }
            }
            if completions < MAX_COMPLETIONS
                && let Some((slot, id, status)) = self.env.async_done.pop()
            {
                completions += 1;
                let mut ctx = Ctx::new(slot, Kind::Cb(Callback::AsyncComplete));
                ctx.async_id = id;
                ctx.async_status = status;
                self.spawn_cb(engine, slot, Callback::AsyncComplete, ctx);
                continue;
            }
            if !pgs_delivered && std::mem::take(&mut self.env.pgs_changed) {
                pgs_delivered = true;
                for slot in 0..self.states.len() as u8 {
                    self.spawn_cb(
                        engine,
                        slot,
                        Callback::PgsChanged,
                        Ctx::new(slot, Kind::Cb(Callback::PgsChanged)),
                    );
                }
                // Changes made inside pgs_changed are delivered on the next pass.
                if !self.env.work.is_empty() || !self.env.async_done.is_empty() {
                    continue;
                }
                self.env.pgs_changed = false;
            }
            break;
        }
    }

    fn stop_waits(&mut self, engine: &mut dyn KspEngine) {
        while let Some((id, mode)) = self.env.stop_waits.pop() {
            let Some(i) = self
                .threads
                .iter()
                .position(|t| t.live && t.waiting && t.ctx.callback_id == id)
            else {
                continue;
            };
            let t = &mut self.threads[i];
            t.generation = t.generation.wrapping_add(1);
            t.waiting = false;
            if mode == 0 {
                self.resume(engine, i as u16);
            } else {
                self.finish(i as u16);
            }
        }
    }

    fn enabled(&self, slot: u8) -> bool {
        self.states[slot as usize].error.is_none()
    }

    /// Some enabled script has an `on poly_at`: it shapes per-note pressure itself.
    pub fn handles_poly_at(&self) -> bool {
        (0..self.programs.len() as u8).any(|slot| self.entry(slot, Callback::PolyAt).is_some())
    }

    fn entry(&self, slot: u8, cb: Callback) -> Option<u32> {
        if self.enabled(slot) {
            self.programs[slot as usize].callback(cb)
        } else {
            None
        }
    }

    fn handle(&mut self, engine: &mut dyn KspEngine, w: Work) {
        let slots = self.programs.len() as u8;
        match w {
            Work::Note { event, slot } => {
                let Some(e) = self.env.events.get_mut(event) else {
                    return;
                };
                if std::mem::take(&mut e.ignored) {
                    if e.length == NoteLength::Sample {
                        self.env.events.free(event);
                    }
                    return;
                }
                if slot >= slots {
                    return self.play(engine, event);
                }
                e.reached = slot + 1;
                match self.entry(slot, Callback::Note) {
                    Some(_) => {
                        let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Note));
                        ctx.event = event;
                        ctx.poly_row = Event::index(event) as u32;
                        ctx.forward = Forward::Note;
                        self.spawn_cb(engine, slot, Callback::Note, ctx);
                    }
                    None => self.env.queue(Work::Note {
                        event,
                        slot: slot + 1,
                    }),
                }
            }
            Work::Release { event, slot } => {
                let Some(e) = self.env.events.get_mut(event) else {
                    return;
                };
                if slot >= slots {
                    if let Some(v) = e.voice.take() {
                        engine.note_off(self.env.offset, v, &e.spec(event));
                    }
                    return self.env.events.free(event);
                }
                if slot >= e.reached || e.released & (1 << slot) != 0 {
                    return self.env.events.free(event);
                }
                e.released |= 1 << slot;
                let children = e.children;
                let count = e.child_count as usize;
                for &child in &children[..count] {
                    if self
                        .env
                        .events
                        .get(child)
                        .is_some_and(|c| c.follows_parent && c.origin == slot + 1)
                    {
                        self.env.queue(Work::Release {
                            event: child,
                            slot: slot + 1,
                        });
                    }
                }
                match self.entry(slot, Callback::Release) {
                    Some(_) => {
                        let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Release));
                        ctx.event = event;
                        ctx.poly_row = Event::index(event) as u32;
                        ctx.forward = Forward::Release;
                        self.spawn_cb(engine, slot, Callback::Release, ctx);
                    }
                    None => self.env.queue(Work::Release {
                        event,
                        slot: slot + 1,
                    }),
                }
            }
            Work::Controller { cc, value, slot } => {
                if slot >= slots {
                    return engine.controller(self.env.offset, cc, value);
                }
                self.write_sys(slot, SysArray::Cc, cc as usize, value);
                self.write_sys(slot, SysArray::CcTouched, cc as usize, 1);
                let mut ctx = Ctx::new(slot, Kind::Cb(Callback::Controller));
                ctx.cc = i32::from(cc);
                ctx.value = value;
                ctx.forward = Forward::Controller;
                if !self.spawn_cb(engine, slot, Callback::Controller, ctx) {
                    self.write_sys(slot, SysArray::CcTouched, cc as usize, 0);
                    self.env.queue(Work::Controller {
                        cc,
                        value,
                        slot: slot + 1,
                    });
                }
            }
            Work::PolyAt { note, value, slot } => {
                if slot >= slots {
                    return;
                }
                self.write_sys(slot, SysArray::PolyAt, note as usize, value);
                let mut ctx = Ctx::new(slot, Kind::Cb(Callback::PolyAt));
                ctx.note = i32::from(note);
                ctx.value = value;
                ctx.forward = Forward::PolyAt;
                if !self.spawn_cb(engine, slot, Callback::PolyAt, ctx) {
                    self.env.queue(Work::PolyAt {
                        note,
                        value,
                        slot: slot + 1,
                    });
                }
            }
            Work::Rpn {
                nrpn,
                address,
                value,
                slot,
            } => {
                if slot >= slots {
                    return;
                }
                let cb = if nrpn { Callback::Nrpn } else { Callback::Rpn };
                let mut ctx = Ctx::new(slot, Kind::Cb(cb));
                ctx.cc = address;
                ctx.value = value;
                ctx.forward = Forward::Rpn { nrpn };
                if !self.spawn_cb(engine, slot, cb, ctx) {
                    self.env.queue(Work::Rpn {
                        nrpn,
                        address,
                        value,
                        slot: slot + 1,
                    });
                }
            }
        }
    }

    /// The event passed every slot: start it in the engine.
    fn play(&mut self, engine: &mut dyn KspEngine, event: i32) {
        let at = self.env.offset;
        let Some(e) = self.env.events.get_mut(event) else {
            return;
        };
        e.at_engine = true;
        let voice = engine.play_note(at, &e.spec(event));
        e.voice = voice;
        if let (Some(v), true) = (voice, e.fade_in_us > 0) {
            engine.fade(
                at,
                v,
                Fade::In {
                    duration_us: e.fade_in_us,
                },
            );
        }
    }

    fn write_sys(&mut self, slot: u8, a: SysArray, i: usize, value: i32) {
        let (prog, state) = (
            &self.programs[slot as usize],
            &mut self.states[slot as usize],
        );
        if let Some(v) = prog.sys_arrays[a as usize] {
            state.mem.ints[prog.vars[v as usize].slot as usize + i] = value;
            self.changes += 1;
        }
    }

    fn set_sys(&mut self, a: SysArray, i: usize, value: i32) {
        for slot in 0..self.programs.len() as u8 {
            self.write_sys(slot, a, i, value);
        }
    }

    /// Start a callback if the slot defines it. Returns whether it ran.
    fn spawn_cb(&mut self, engine: &mut dyn KspEngine, slot: u8, cb: Callback, ctx: Ctx) -> bool {
        match self.entry(slot, cb) {
            Some(entry) => {
                self.spawn(engine, entry, ctx);
                true
            }
            None => false,
        }
    }

    fn spawn(&mut self, engine: &mut dyn KspEngine, entry: u32, mut ctx: Ctx) {
        let Some(i) = self.free_threads.pop() else {
            self.env
                .note("KSP callback pool exhausted; callback dropped");
            self.forward(ctx);
            return;
        };
        self.env.next_callback_id = self.env.next_callback_id % i32::MAX + 1;
        ctx.callback_id = self.env.next_callback_id;
        if !matches!(ctx.kind, Kind::Cb(Callback::Note | Callback::Release)) {
            ctx.poly_row = POLY_ROWS - 1;
        }
        let t = &mut self.threads[i as usize];
        *t = Thread {
            pc: entry,
            live: true,
            generation: t.generation.wrapping_add(1),
            ctx,
            ..Thread::default()
        };
        self.resume(engine, i);
    }

    fn resume(&mut self, engine: &mut dyn KspEngine, i: u16) {
        self.changes += 1;
        let t = &mut self.threads[i as usize];
        let slot = t.ctx.slot as usize;
        let budget = self
            .env
            .block_fuel
            .min(self.fuel_cap.saturating_sub(t.spent));
        let mut fuel = budget;
        let result = vm::exec(
            &mut Machine {
                prog: &self.programs[slot],
                slot: &mut self.states[slot],
                env: &mut self.env,
                stk: &mut self.stacks,
                engine,
                t,
            },
            &mut fuel,
        );
        self.env.block_fuel -= budget - fuel;
        self.threads[i as usize].spent += budget - fuel;
        match result {
            Ok(Yield::Done) => self.finish(i),
            Ok(Yield::Wait(at)) => {
                let t = &mut self.threads[i as usize];
                t.waiting = true;
                t.spent = 0;
                let generation = t.generation;
                self.env.timer(
                    at,
                    TimerKind::Resume {
                        thread: i,
                        generation,
                    },
                );
                self.yielded(i);
            }
            Ok(Yield::OutOfFuel) if self.threads[i as usize].spent >= self.fuel_cap => {
                let pc = self.threads[i as usize].pc;
                self.env.fault(
                    slot as u8,
                    pc,
                    "KSP callback exceeded its instruction budget",
                );
                self.finish(i);
            }
            Ok(Yield::OutOfFuel) => {
                // Block budget spent: continue at the start of the next block.
                let generation = self.threads[i as usize].generation;
                let at = self.env.clock();
                self.env.timer(
                    at,
                    TimerKind::Resume {
                        thread: i,
                        generation,
                    },
                );
            }
            Err(f) => {
                let pc = self.threads[i as usize].pc;
                self.env.fault(slot as u8, pc, f.0);
                self.finish(i);
            }
        }
    }

    fn finish(&mut self, i: u16) {
        self.yielded(i);
        let t = &mut self.threads[i as usize];
        t.live = false;
        t.generation = t.generation.wrapping_add(1);
        self.free_threads.push(i);
    }

    /// First yield of a callback: pass its event on unless the script ignored it.
    fn yielded(&mut self, i: u16) {
        let ctx = self.threads[i as usize].ctx;
        self.threads[i as usize].ctx.forward = Forward::None;
        self.forward(ctx);
    }

    fn forward(&mut self, ctx: Ctx) {
        let next = ctx.slot + 1;
        match ctx.forward {
            Forward::None => {}
            Forward::Note => {
                let Some(e) = self.env.events.get_mut(ctx.event) else {
                    return;
                };
                if std::mem::take(&mut e.ignored) {
                    if e.length == NoteLength::Sample {
                        self.env.events.free(ctx.event);
                    }
                } else {
                    self.env.queue(Work::Note {
                        event: ctx.event,
                        slot: next,
                    });
                }
            }
            Forward::Release => {
                let Some(e) = self.env.events.get_mut(ctx.event) else {
                    return;
                };
                if !std::mem::take(&mut e.release_ignored) {
                    self.env.queue(Work::Release {
                        event: ctx.event,
                        slot: next,
                    });
                }
            }
            Forward::Controller => {
                let cc = ctx.cc as u8;
                self.write_sys(ctx.slot, SysArray::CcTouched, cc as usize, 0);
                if !ctx.ignore_controller {
                    self.env.queue(Work::Controller {
                        cc,
                        value: ctx.value,
                        slot: next,
                    });
                }
            }
            Forward::PolyAt => {
                if !ctx.ignore_controller {
                    self.env.queue(Work::PolyAt {
                        note: ctx.note as u8,
                        value: ctx.value,
                        slot: next,
                    });
                }
            }
            Forward::Rpn { nrpn } => {
                if !ctx.ignore_controller {
                    self.env.queue(Work::Rpn {
                        nrpn,
                        address: ctx.cc,
                        value: ctx.value,
                        slot: next,
                    });
                }
            }
        }
    }
}

pub fn read_value(mem: &vm::Memory, var: &compile::Var) -> Value {
    let s = var.slot as usize;
    match (var.ty, var.len, var.poly) {
        (_, _, true) => Value::Int(0),
        (Ty::Int, None, _) => Value::Int(mem.ints[s]),
        (Ty::Real, None, _) => Value::Real(mem.reals[s]),
        (Ty::Str, None, _) => Value::Text(mem.strs[s].clone()),
        (Ty::Int, Some(n), _) => Value::Array(
            mem.ints[s..s + n as usize]
                .iter()
                .map(|&x| Value::Int(x))
                .collect(),
        ),
        (Ty::Real, Some(n), _) => Value::Array(
            mem.reals[s..s + n as usize]
                .iter()
                .map(|&x| Value::Real(x))
                .collect(),
        ),
        (Ty::Str, Some(n), _) => Value::Array(
            mem.strs[s..s + n as usize]
                .iter()
                .map(|x| Value::Text(x.clone()))
                .collect(),
        ),
    }
}

/// Replace `t` with as much of `s` as fits its capacity, without allocating.
/// Returns whether `t` changed.
pub(super) fn copy_text(t: &mut String, s: &str) -> bool {
    if t == s {
        return false;
    }
    t.clear();
    t.push_str(&s[..s.floor_char_boundary(t.capacity())]);
    true
}

/// Give a string room to grow before a refresh must cut it.
fn room(t: &mut String) {
    t.reserve(t.len().max(SNAPSHOT_SLACK));
}

fn each_text_in(value: &mut Value, f: &mut impl FnMut(&mut String)) {
    match value {
        Value::Text(t) => f(t),
        Value::Array(items) => items.iter_mut().for_each(|v| each_text_in(v, f)),
        _ => {}
    }
}

/// Copy current values into a value shaped by [`read_value`], without
/// reshaping it; returns whether it changed.
pub(super) fn refresh_value(mem: &vm::Memory, var: &compile::Var, value: &mut Value) -> bool {
    refresh_range(mem, var, value, 0..usize::MAX)
}

/// [`refresh_value`] for the array elements in `range` (a scalar is element 0).
fn refresh_range(
    mem: &vm::Memory,
    var: &compile::Var,
    value: &mut Value,
    range: std::ops::Range<usize>,
) -> bool {
    if var.poly {
        return false;
    }
    fn set<T: PartialEq + Copy>(d: &mut T, x: T) -> bool {
        let changed = *d != x;
        *d = x;
        changed
    }
    let one = |i: usize, v: &mut Value| match (var.ty, v) {
        (Ty::Int, Value::Int(n)) => set(n, mem.ints[i]),
        (Ty::Real, Value::Real(n)) => set(n, mem.reals[i]),
        (Ty::Str, Value::Text(t)) => copy_text(t, &mem.strs[i]),
        _ => false,
    };
    let s = var.slot as usize;
    match (var.len, value) {
        (None, v) if range.start == 0 && !range.is_empty() => one(s, v),
        (Some(n), Value::Array(items)) => {
            let end = range.end.min(n as usize).min(items.len());
            let start = range.start.min(end);
            let mut changed = false;
            for (i, v) in items[start..end].iter_mut().enumerate() {
                changed |= one(s + start + i, v);
            }
            changed
        }
        _ => false,
    }
}

/// Where an incremental refresh stands; start from the default.
#[derive(Clone, Copy, Debug, Default)]
pub struct Refresh {
    slot: usize,
    item: usize,
    at: usize,
    /// Something differed from the buffer so far.
    pub changed: bool,
}

/// Whether `saved`, refreshed by [`Runtime::refresh_persistence`], holds
/// every string whole. Strings that may have been cut get twice the room for
/// the next refresh; a snapshot that is not whole should not be saved.
pub fn settle_persistence(saved: &mut [Persisted]) -> bool {
    let mut whole = true;
    each_text(saved, |t| {
        // A cut lands within a UTF-8 sequence (< 4 bytes) of the end.
        if t.capacity() - t.len() < 4 {
            t.reserve(t.capacity());
            whole = false;
        }
    });
    whole
}

fn each_text(saved: &mut [Persisted], mut f: impl FnMut(&mut String)) {
    for value in saved.iter_mut().flat_map(|p| p.values_mut()) {
        match value {
            Value::Text(t) => f(t),
            Value::Array(items) => items.iter_mut().for_each(|v| {
                if let Value::Text(t) = v {
                    f(t);
                }
            }),
            _ => {}
        }
    }
}

/// Write a saved value back; mismatched types or lengths are ignored element-wise.
pub fn write_value(mem: &mut vm::Memory, var: &compile::Var, value: &Value) {
    if var.poly {
        return;
    }
    let s = var.slot as usize;
    let one = |mem: &mut vm::Memory, i: usize, v: &Value| match (var.ty, v) {
        (Ty::Int, Value::Int(n)) => mem.ints[i] = *n,
        (Ty::Real, Value::Real(n)) => mem.reals[i] = *n,
        (Ty::Str, Value::Text(t)) => {
            mem.strs[i].clear();
            mem.strs[i].push_str(t);
        }
        _ => {}
    };
    match (var.len, value) {
        (None, v) => one(mem, s, v),
        (Some(n), Value::Array(items)) => {
            for (i, v) in items.iter().take(n as usize).enumerate() {
                one(mem, s + i, v);
            }
        }
        _ => {}
    }
}
