#!/usr/bin/env python3
"""Generate docs/architecture-v2/KSP_COVERAGE.md.

    ksp_coverage.py SCRIPTS_DIR CORPUS_OUT > docs/architecture-v2/KSP_COVERAGE.md

SCRIPTS_DIR comes from `cargo run --release -p sampler-kontakt --example
dump_scripts ROOT SCRIPTS_DIR`; CORPUS_OUT is the output of
`KSP_VERBOSE=1 cargo run --release -p sampler-ksp --example corpus SCRIPTS_DIR`.
Library content stays in the cache directory; only counts are written.

Columns: corpus = instruments whose scripts mention the symbol (comments and
strings removed); parse = the frontend knows the name; lower = how call sites
lower in the corpus (Native, Approximate, Effect, Host, Ignored); runtime =
what executes; UI = the interface model reads it; test = a test names it.
"""
import collections
import glob
import os
import re
import sys

scripts, corpus_out = sys.argv[1], sys.argv[2]
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = lambda *p: open(os.path.join(root, *p), errors="ignore").read()

# --- symbols -------------------------------------------------------------
sections, cur = collections.OrderedDict(), None
for line in src("docs/architecture-v2/KSP_SYMBOLS.md").splitlines():
    if line.startswith("## "):
        cur = line[3:].split(" (")[0]
        sections[cur] = []
    elif cur and line and not line.startswith(("```", "#")):
        sections[cur].append(line.lstrip("- ").replace("on ", "", 1) if cur == "Callbacks" else line.strip())

# --- corpus use ----------------------------------------------------------
uses = collections.defaultdict(set)
for line in open(os.path.join(scripts, "manifest.tsv")):
    h, path = line.rstrip("\n").split("\t", 1)
    uses[h].add(path)
tok = re.compile(r"[$%~@!?]?[A-Za-z_][A-Za-z_0-9.]*")
instruments = collections.defaultdict(set)
for f in glob.glob(os.path.join(scripts, "*.ksp")):
    h = os.path.basename(f)[:-4]
    text = open(f, errors="ignore").read()
    text = re.sub(r'"[^"\n]*"', '""', text)
    text = re.sub(r"\{[^}]*\}", " ", text)
    words = {w.lstrip("$%~@!?") for w in tok.findall(text)}
    for w in words:
        instruments["bare:" + w] |= uses[h]
    for c in set(re.findall(r"^\s*on\s+([a-z_]+)", text, re.M)):
        instruments["on:" + c] |= uses[h]

# --- implementation facts ------------------------------------------------
builtins = src("crates/sampler-ksp/src/builtins.rs")
known = set(re.findall(r'"([$%~@!?]?[A-Za-z_][A-Za-z_0-9]*)"', builtins))
cover = collections.defaultdict(dict)
for m in re.finditer(r"^\s+(\S+) (Native|Approximate|Effect|Host|Ignored) (\d+)$", open(corpus_out).read(), re.M):
    cover[m[1]][m[2]] = int(m[3])
lower = src("crates/sampler-ksp/src/lower.rs")
engine_native = set(re.findall(r"ENGINE_PAR_([A-Z_0-9]+)", lower))
kinds = set(re.findall(r"^    (\w+),?$", src("crates/sampler-ksp/src/hir.rs").split("pub enum CallbackKind")[1].split("}")[0], re.M))
ui_src = "".join(src("crates/sampler-ksp", "src", f) for f in ("ui.rs", "model.rs")) if False else (
    src("crates/sampler-ksp/src/ui.rs") + src("crates/sampler-ksp/src/model.rs") + src("crates/sampler-ksp/src/lib.rs"))
tests = "".join(open(f, errors="ignore").read() for pat in (
    "crates/sampler-ksp/tests/*.rs", "crates/sampler-core/tests/*.rs", "crates/sampler-kontakt/tests/*.rs")
    for f in glob.glob(os.path.join(root, pat)))

def mentioned(text, name):
    bare = name.lstrip("$%~@!?")
    return re.search(r"(?<![A-Za-z0-9_])" + re.escape(bare) + r"(?![A-Za-z0-9_])", text) is not None

def used(name):
    return len(instruments["bare:" + name.lstrip("$%~@!?")])

def classes(name):
    c = cover.get(name)
    if not c:
        return None
    return "+".join(k for k, _ in sorted(c.items(), key=lambda kv: -kv[1]))

rows_total = collections.Counter()
out = []
out.append("# KSP coverage\n")
out.append("Generated by `tools/ksp_coverage.py` from [KSP_SYMBOLS.md](KSP_SYMBOLS.md) (Kontakt 8 KSP Reference Manual), the installed corpus and the sampler-ksp sources. Regenerate after every KSP change; do not edit by hand.\n")
out.append("Columns: **corpus** = instruments whose scripts mention the symbol; **parse** = the frontend knows the name (`family` = accepted by prefix as an opaque id); **lower** = how corpus call sites lower (Native executed, Approximate documented approximation, Effect/Host handed to the host through the outbox, Ignored warned and dropped, `-` = never lowered in the corpus); **runtime** = what the engine does; **UI** = the interface model reads it; **test** = a test names it. Counts are text matches, not proofs of reachability.\n")
for section, names in sections.items():
    table = []
    for name in sorted(set(names)):
        if section == "Callbacks":
            n = len(instruments["on:" + name])
            parse = "yes" if name in {"init", "note", "release", "controller", "poly_at", "ui_control", "listener", "pgs_changed", "persistence_changed", "async_complete", "rpn", "nrpn"} else "no"
            lower = runtime = "native" if parse == "yes" else "-"
        else:
            n = used(name)
            kn = name in known
            fam = re.match(r"\$(ENGINE_PAR|CONTROL_PAR|EVENT_PAR|ZONE_PAR|LOOP_PAR)_", name) is not None
            parse = "yes" if kn else ("family" if fam else "no")
            c = classes(name)
            if section.startswith("$ENGINE_PAR"):
                short = name[len("$ENGINE_PAR_"):]
                lower = "-" if not n else ("Native" if short in engine_native else "Effect")
                runtime = ("native" if short in engine_native else "host effect; value mirrored for get_engine_par") if n else "-"
            elif c:
                lower = c
                runtime = "native" if c.startswith("Native") else {"Approximate": "approximate", "Effect": "host effect", "Host": "host service", "Ignored": "ignored"}[c.split("+")[0]]
            else:
                lower = "-"
                runtime = "constant" if name.startswith("$") and kn else ("not lowered" if not kn else "compile time / no op")
        ui = "yes" if mentioned(ui_src, name) else "-"
        test = "yes" if mentioned(tests, name) else "-"
        table.append((name, n, parse, lower, runtime, ui, test))
        rows_total[(section, parse)] += 1
    table.sort(key=lambda r: (-r[1], r[0]))
    used_rows = sum(1 for r in table if r[1])
    gaps = sum(1 for r in table if r[1] and (r[2] == "no" or r[4] in ("ignored", "not lowered", "host effect; value mirrored for get_engine_par")))
    out.append(f"\n## {section}\n\n{len(table)} symbols, {used_rows} used by the corpus, {gaps} of those not fully real (unparsed, ignored or host-only).\n")
    out.append("| symbol | corpus | parse | lower | runtime | UI | test |\n|---|---|---|---|---|---|---|")
    for r in table:
        out.append("| " + " | ".join(f"`{x}`" if i == 0 else str(x) for i, x in enumerate(r)) + " |")
print("\n".join(out))
