#!/usr/bin/env python3
"""Pedal scenarios from sampler-native/tests/pedals.rs as one scenario file (12 s per scenario, controllers reset between).
Usage: pedal_suite.py LOWKEY HIGHKEY > suite.txt   (a=low, b=low+4, c=high)"""
import sys
lo, hi = int(sys.argv[1]), int(sys.argv[2]); a, b, c = lo, lo + 4, hi
S = {
 'sustain': [(0,'pedal',127),(.1,'on',a,100),(.1,'on',b,90),(.4,'off',a),(.4,'off',b),(1,'pedal',0)],
 'retrigger': [(0,'pedal',127),(.1,'on',a,100),(.2,'off',a),(.3,'on',a,80),(.4,'off',a),(.8,'pedal',0),(1,'on',b,100),(1.1,'on',b,70),(1.2,'off',b),(1.3,'off',b),(1.4,'off',b)],
 'pedal_after_notes': [(0,'on',a,100),(0,'on',b,100),(.2,'off',a),(.3,'pedal',127),(.5,'off',b),(1,'pedal',0)],
 'pedal_up_while_held': [(0,'pedal',127),(.1,'on',a,100),(.1,'on',b,100),(.3,'pedal',0),(.35,'off',a),(.4,'pedal',127),(.6,'off',b),(.9,'pedal',0)],
 'half_pedal': [(0,'pedal',63),(.1,'on',a,100),(.2,'off',a),(.3,'pedal',64),(.35,'on',b,100),(.4,'off',b),(.5,'pedal',100),(.55,'pedal',64),(.6,'pedal',40),(.7,'pedal',127),(.75,'on',c,100),(.8,'off',c),(1.2,'pedal',0)],
 'sostenuto': [(.1,'on',a,100),(.1,'on',b,100),(.2,'off',a),(.2,'cc',66,127),(.3,'off',b),(.5,'cc',66,0),(.7,'on',c,100),(.8,'off',c)],
 'sostenuto_after': [(0,'on',a,100),(0,'on',c,100),(.05,'off',c),(.1,'cc',66,127),(.2,'on',b,100),(.25,'cc',66,100),(.3,'off',a),(.4,'off',b),(.5,'on',a,100),(.6,'off',a),(1,'cc',66,0)],
 'soft_pedal': [(0,'cc',67,127),(.1,'on',a,100),(.6,'off',a),(1,'cc',67,0),(1.1,'on',a,100),(1.6,'off',a)],
}
T = 0.0
print('# generated by pedal_suite.py')
for name, ev in S.items():
    print(f'# {name} starts at {T}')
    for e in ev:
        print(f'{T+e[0]:.3f}', *e[1:])
    print(f'{T+10:.3f} pedal 0'); print(f'{T+10:.3f} cc 66 0'); print(f'{T+10:.3f} cc 67 0'); print(f'{T+10.1:.3f} cc 123 0')
    T += 14.0
print(f'{T} end')
